#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Sep 04 17:33:09 UTC 2020
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_axis_gp_bridge_behav -key {Behavioral:sim_1:Functional:tb_axis_gp_bridge} -tclbatch tb_axis_gp_bridge.tcl -view /home/justin/paulchowresearch2020/Galapagos/finn_galapagos_bridge/axis_galapagos_bridge/tb_axis_gp_bridge_behav.wcfg -log simulate.log"
xsim tb_axis_gp_bridge_behav -key {Behavioral:sim_1:Functional:tb_axis_gp_bridge} -tclbatch tb_axis_gp_bridge.tcl -view /home/justin/paulchowresearch2020/Galapagos/finn_galapagos_bridge/axis_galapagos_bridge/tb_axis_gp_bridge_behav.wcfg -log simulate.log

