#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.3 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Aug 28 13:00:50 EDT 2020
# SW Build 2405991 on Thu Dec  6 23:36:41 MST 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim tb_axis_gp_bridge_behav -key {Behavioral:sim_1:Functional:tb_axis_gp_bridge} -tclbatch tb_axis_gp_bridge.tcl -view /home/justin/jhai/paulchowresearch2020/Galapagos/finn_galapagos_bridge/axis_galapagos_bridge/tb_data_width_converter_behav.wcfg -view /home/justin/jhai/paulchowresearch2020/Galapagos/finn_galapagos_bridge/axis_galapagos_bridge/tb_gp_axis_bridge_behav.wcfg -log simulate.log
