webtalk_init -webtalk_dir /home/justin/jhai/paulchowresearch2020/Galapagos/finn_galapagos_bridge/finn_galapagos_bridge.sim/sim_1/behav/xsim/xsim.dir/tb_gp_axis_bridge_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Aug  6 18:32:58 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174111048_179741397_210699440_801" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d0a95705-d93c-4588-ae32-0d6270c1d0a6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "af01657b14104413a1550bf285f0144c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3500.107 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "560 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "115904_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2701083673 -regid "174111048_179741397_210699440_801" -xml /home/justin/jhai/paulchowresearch2020/Galapagos/finn_galapagos_bridge/finn_galapagos_bridge.sim/sim_1/behav/xsim/xsim.dir/tb_gp_axis_bridge_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/justin/jhai/paulchowresearch2020/Galapagos/finn_galapagos_bridge/finn_galapagos_bridge.sim/sim_1/behav/xsim/xsim.dir/tb_gp_axis_bridge_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/justin/jhai/paulchowresearch2020/Galapagos/finn_galapagos_bridge/finn_galapagos_bridge.sim/sim_1/behav/xsim/xsim.dir/tb_gp_axis_bridge_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
