#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Sep 02 00:30:25 UTC 2020
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto af01657b14104413a1550bf285f0144c --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L secureip --snapshot tb_axis_gp_bridge_func_synth xil_defaultlib.tb_axis_gp_bridge xil_defaultlib.glbl -log elaborate.log"
xelab -wto af01657b14104413a1550bf285f0144c --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L secureip --snapshot tb_axis_gp_bridge_func_synth xil_defaultlib.tb_axis_gp_bridge xil_defaultlib.glbl -log elaborate.log

