// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3_HH_
#define _StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "StreamingFCLayer_Batch_3_Matrix_Vector_Activa.h"

namespace ap_rtl {

struct StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3 : public sc_module {
    // Port declarations 11
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_lv<8> > in0_V_V_TDATA;
    sc_in< sc_logic > in0_V_V_TVALID;
    sc_out< sc_logic > in0_V_V_TREADY;
    sc_in< sc_lv<80> > weights_V_V_TDATA;
    sc_in< sc_logic > weights_V_V_TVALID;
    sc_out< sc_logic > weights_V_V_TREADY;
    sc_out< sc_lv<320> > out_V_V_TDATA;
    sc_out< sc_logic > out_V_V_TVALID;
    sc_in< sc_logic > out_V_V_TREADY;


    // Module declarations
    StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3(sc_module_name name);
    SC_HAS_PROCESS(StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3);

    ~StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    StreamingFCLayer_Batch_3_Matrix_Vector_Activa* grp_Matrix_Vector_Activa_fu_28;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_lv<8> > in0_V_V_0_data_out;
    sc_signal< sc_logic > in0_V_V_0_vld_in;
    sc_signal< sc_logic > in0_V_V_0_vld_out;
    sc_signal< sc_logic > in0_V_V_0_ack_in;
    sc_signal< sc_logic > in0_V_V_0_ack_out;
    sc_signal< sc_lv<8> > in0_V_V_0_payload_A;
    sc_signal< sc_lv<8> > in0_V_V_0_payload_B;
    sc_signal< sc_logic > in0_V_V_0_sel_rd;
    sc_signal< sc_logic > in0_V_V_0_sel_wr;
    sc_signal< sc_logic > in0_V_V_0_sel;
    sc_signal< sc_logic > in0_V_V_0_load_A;
    sc_signal< sc_logic > in0_V_V_0_load_B;
    sc_signal< sc_lv<2> > in0_V_V_0_state;
    sc_signal< sc_logic > in0_V_V_0_state_cmp_full;
    sc_signal< sc_lv<80> > weights_V_V_0_data_out;
    sc_signal< sc_logic > weights_V_V_0_vld_in;
    sc_signal< sc_logic > weights_V_V_0_vld_out;
    sc_signal< sc_logic > weights_V_V_0_ack_in;
    sc_signal< sc_logic > weights_V_V_0_ack_out;
    sc_signal< sc_lv<80> > weights_V_V_0_payload_A;
    sc_signal< sc_lv<80> > weights_V_V_0_payload_B;
    sc_signal< sc_logic > weights_V_V_0_sel_rd;
    sc_signal< sc_logic > weights_V_V_0_sel_wr;
    sc_signal< sc_logic > weights_V_V_0_sel;
    sc_signal< sc_logic > weights_V_V_0_load_A;
    sc_signal< sc_logic > weights_V_V_0_load_B;
    sc_signal< sc_lv<2> > weights_V_V_0_state;
    sc_signal< sc_logic > weights_V_V_0_state_cmp_full;
    sc_signal< sc_lv<320> > out_V_V_1_data_out;
    sc_signal< sc_logic > out_V_V_1_vld_in;
    sc_signal< sc_logic > out_V_V_1_vld_out;
    sc_signal< sc_logic > out_V_V_1_ack_in;
    sc_signal< sc_logic > out_V_V_1_ack_out;
    sc_signal< sc_lv<320> > out_V_V_1_payload_A;
    sc_signal< sc_lv<320> > out_V_V_1_payload_B;
    sc_signal< sc_logic > out_V_V_1_sel_rd;
    sc_signal< sc_logic > out_V_V_1_sel_wr;
    sc_signal< sc_logic > out_V_V_1_sel;
    sc_signal< sc_logic > out_V_V_1_load_A;
    sc_signal< sc_logic > out_V_V_1_load_B;
    sc_signal< sc_lv<2> > out_V_V_1_state;
    sc_signal< sc_logic > out_V_V_1_state_cmp_full;
    sc_signal< sc_logic > grp_Matrix_Vector_Activa_fu_28_ap_start;
    sc_signal< sc_logic > grp_Matrix_Vector_Activa_fu_28_ap_done;
    sc_signal< sc_logic > grp_Matrix_Vector_Activa_fu_28_ap_idle;
    sc_signal< sc_logic > grp_Matrix_Vector_Activa_fu_28_ap_ready;
    sc_signal< sc_logic > grp_Matrix_Vector_Activa_fu_28_in_V_V_TVALID;
    sc_signal< sc_logic > grp_Matrix_Vector_Activa_fu_28_in_V_V_TREADY;
    sc_signal< sc_lv<320> > grp_Matrix_Vector_Activa_fu_28_out_V_V_TDATA;
    sc_signal< sc_logic > grp_Matrix_Vector_Activa_fu_28_out_V_V_TVALID;
    sc_signal< sc_logic > grp_Matrix_Vector_Activa_fu_28_out_V_V_TREADY;
    sc_signal< sc_logic > grp_Matrix_Vector_Activa_fu_28_weight_V_V_TVALID;
    sc_signal< sc_logic > grp_Matrix_Vector_Activa_fu_28_weight_V_V_TREADY;
    sc_signal< sc_logic > grp_Matrix_Vector_Activa_fu_28_ap_start_reg;
    sc_signal< sc_lv<4> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<4> > ap_NS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<4> ap_ST_fsm_state1;
    static const sc_lv<4> ap_ST_fsm_state2;
    static const sc_lv<4> ap_ST_fsm_state3;
    static const sc_lv<4> ap_ST_fsm_state4;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_rst_n_inv();
    void thread_grp_Matrix_Vector_Activa_fu_28_ap_start();
    void thread_grp_Matrix_Vector_Activa_fu_28_in_V_V_TVALID();
    void thread_grp_Matrix_Vector_Activa_fu_28_out_V_V_TREADY();
    void thread_grp_Matrix_Vector_Activa_fu_28_weight_V_V_TVALID();
    void thread_in0_V_V_0_ack_in();
    void thread_in0_V_V_0_ack_out();
    void thread_in0_V_V_0_data_out();
    void thread_in0_V_V_0_load_A();
    void thread_in0_V_V_0_load_B();
    void thread_in0_V_V_0_sel();
    void thread_in0_V_V_0_state_cmp_full();
    void thread_in0_V_V_0_vld_in();
    void thread_in0_V_V_0_vld_out();
    void thread_in0_V_V_TREADY();
    void thread_out_V_V_1_ack_in();
    void thread_out_V_V_1_ack_out();
    void thread_out_V_V_1_data_out();
    void thread_out_V_V_1_load_A();
    void thread_out_V_V_1_load_B();
    void thread_out_V_V_1_sel();
    void thread_out_V_V_1_state_cmp_full();
    void thread_out_V_V_1_vld_in();
    void thread_out_V_V_1_vld_out();
    void thread_out_V_V_TDATA();
    void thread_out_V_V_TVALID();
    void thread_weights_V_V_0_ack_in();
    void thread_weights_V_V_0_ack_out();
    void thread_weights_V_V_0_data_out();
    void thread_weights_V_V_0_load_A();
    void thread_weights_V_V_0_load_B();
    void thread_weights_V_V_0_sel();
    void thread_weights_V_V_0_state_cmp_full();
    void thread_weights_V_V_0_vld_in();
    void thread_weights_V_V_0_vld_out();
    void thread_weights_V_V_TREADY();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
