// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module StreamingFCLayer_Batch_3_Matrix_Vector_Activa (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_V_V_TDATA,
        in_V_V_TVALID,
        in_V_V_TREADY,
        out_V_V_TDATA,
        out_V_V_TVALID,
        out_V_V_TREADY,
        weight_V_V_TDATA,
        weight_V_V_TVALID,
        weight_V_V_TREADY
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state4 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] in_V_V_TDATA;
input   in_V_V_TVALID;
output   in_V_V_TREADY;
output  [319:0] out_V_V_TDATA;
output   out_V_V_TVALID;
input   out_V_V_TREADY;
input  [79:0] weight_V_V_TDATA;
input   weight_V_V_TVALID;
output   weight_V_V_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_V_V_TREADY;
reg out_V_V_TVALID;
reg weight_V_V_TREADY;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    in_V_V_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire   [0:0] exitcond_fu_376_p2;
wire   [0:0] tmp_fu_391_p2;
reg    out_V_V_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] tmp_9_reg_3867;
reg    weight_V_V_TDATA_blk_n;
reg   [3:0] i_reg_345;
reg    ap_predicate_op53_read_state2;
reg    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_state3_io;
reg    ap_block_pp0_stage0_11001;
wire   [3:0] i_1_fu_382_p2;
wire   [0:0] tmp_6_fu_716_p2;
reg   [0:0] tmp_6_reg_3653;
wire   [0:0] tmp_16_0_4_fu_896_p2;
reg   [0:0] tmp_16_0_4_reg_3667;
wire   [0:0] tmp_16_0_5_fu_916_p2;
reg   [0:0] tmp_16_0_5_reg_3672;
wire   [0:0] tmp_16_0_6_fu_936_p2;
reg   [0:0] tmp_16_0_6_reg_3677;
wire   [2:0] tmp15_fu_992_p2;
reg   [2:0] tmp15_reg_3682;
wire   [0:0] tmp_16_1_4_fu_1132_p2;
reg   [0:0] tmp_16_1_4_reg_3687;
wire   [0:0] tmp_16_1_5_fu_1144_p2;
reg   [0:0] tmp_16_1_5_reg_3692;
wire   [0:0] tmp_16_1_6_fu_1156_p2;
reg   [0:0] tmp_16_1_6_reg_3697;
wire   [2:0] tmp30_fu_1204_p2;
reg   [2:0] tmp30_reg_3702;
wire   [0:0] tmp_16_2_4_fu_1344_p2;
reg   [0:0] tmp_16_2_4_reg_3707;
wire   [0:0] tmp_16_2_5_fu_1356_p2;
reg   [0:0] tmp_16_2_5_reg_3712;
wire   [0:0] tmp_16_2_6_fu_1368_p2;
reg   [0:0] tmp_16_2_6_reg_3717;
wire   [2:0] tmp45_fu_1416_p2;
reg   [2:0] tmp45_reg_3722;
wire   [0:0] tmp_16_3_4_fu_1556_p2;
reg   [0:0] tmp_16_3_4_reg_3727;
wire   [0:0] tmp_16_3_5_fu_1568_p2;
reg   [0:0] tmp_16_3_5_reg_3732;
wire   [0:0] tmp_16_3_6_fu_1580_p2;
reg   [0:0] tmp_16_3_6_reg_3737;
wire   [2:0] tmp60_fu_1628_p2;
reg   [2:0] tmp60_reg_3742;
wire   [0:0] tmp_16_4_4_fu_1768_p2;
reg   [0:0] tmp_16_4_4_reg_3747;
wire   [0:0] tmp_16_4_5_fu_1780_p2;
reg   [0:0] tmp_16_4_5_reg_3752;
wire   [0:0] tmp_16_4_6_fu_1792_p2;
reg   [0:0] tmp_16_4_6_reg_3757;
wire   [2:0] tmp75_fu_1840_p2;
reg   [2:0] tmp75_reg_3762;
wire   [0:0] tmp_16_5_4_fu_1980_p2;
reg   [0:0] tmp_16_5_4_reg_3767;
wire   [0:0] tmp_16_5_5_fu_1992_p2;
reg   [0:0] tmp_16_5_5_reg_3772;
wire   [0:0] tmp_16_5_6_fu_2004_p2;
reg   [0:0] tmp_16_5_6_reg_3777;
wire   [2:0] tmp90_fu_2052_p2;
reg   [2:0] tmp90_reg_3782;
wire   [0:0] tmp_16_6_4_fu_2192_p2;
reg   [0:0] tmp_16_6_4_reg_3787;
wire   [0:0] tmp_16_6_5_fu_2204_p2;
reg   [0:0] tmp_16_6_5_reg_3792;
wire   [0:0] tmp_16_6_6_fu_2216_p2;
reg   [0:0] tmp_16_6_6_reg_3797;
wire   [2:0] tmp105_fu_2264_p2;
reg   [2:0] tmp105_reg_3802;
wire   [0:0] tmp_16_7_4_fu_2404_p2;
reg   [0:0] tmp_16_7_4_reg_3807;
wire   [0:0] tmp_16_7_5_fu_2416_p2;
reg   [0:0] tmp_16_7_5_reg_3812;
wire   [0:0] tmp_16_7_6_fu_2428_p2;
reg   [0:0] tmp_16_7_6_reg_3817;
wire   [2:0] tmp120_fu_2476_p2;
reg   [2:0] tmp120_reg_3822;
wire   [0:0] tmp_16_8_4_fu_2616_p2;
reg   [0:0] tmp_16_8_4_reg_3827;
wire   [0:0] tmp_16_8_5_fu_2628_p2;
reg   [0:0] tmp_16_8_5_reg_3832;
wire   [0:0] tmp_16_8_6_fu_2640_p2;
reg   [0:0] tmp_16_8_6_reg_3837;
wire   [2:0] tmp135_fu_2688_p2;
reg   [2:0] tmp135_reg_3842;
wire   [0:0] tmp_16_9_4_fu_2824_p2;
reg   [0:0] tmp_16_9_4_reg_3847;
wire   [0:0] tmp_16_9_5_fu_2836_p2;
reg   [0:0] tmp_16_9_5_reg_3852;
wire   [0:0] tmp_16_9_6_fu_2848_p2;
reg   [0:0] tmp_16_9_6_reg_3857;
wire   [2:0] tmp150_fu_2896_p2;
reg   [2:0] tmp150_reg_3862;
wire   [0:0] tmp_9_fu_2908_p2;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg   [7:0] ap_phi_mux_act_m_val_V_phi_fu_359_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_act_m_val_V_reg_356;
wire   [7:0] inElem_V_fu_428_p10;
reg   [31:0] accu_0_0_V_1_fu_246;
wire   [31:0] accu_0_0_V_fu_3075_p2;
reg   [31:0] accu_0_1_V_1_fu_250;
wire   [31:0] accu_0_1_V_fu_3115_p2;
reg   [31:0] accu_0_2_V_1_fu_254;
wire   [31:0] accu_0_2_V_fu_3155_p2;
reg   [31:0] accu_0_3_V_1_fu_258;
wire   [31:0] accu_0_3_V_fu_3195_p2;
reg   [31:0] accu_0_4_V_1_fu_262;
wire   [31:0] accu_0_4_V_fu_3235_p2;
reg   [31:0] accu_0_5_V_1_fu_266;
wire   [31:0] accu_0_5_V_fu_3275_p2;
reg   [31:0] accu_0_6_V_1_fu_270;
wire   [31:0] accu_0_6_V_fu_3315_p2;
reg   [31:0] accu_0_7_V_1_fu_274;
wire   [31:0] accu_0_7_V_fu_3355_p2;
reg   [31:0] accu_0_8_V_1_fu_278;
wire   [31:0] accu_0_8_V_fu_3395_p2;
reg   [31:0] accu_0_9_V_1_fu_282;
wire   [31:0] accu_0_9_V_fu_3435_p2;
reg   [31:0] sf_fu_286;
wire   [31:0] sf_1_fu_2902_p2;
reg   [31:0] nf_fu_290;
wire   [31:0] p_s_fu_2928_p3;
reg   [7:0] inputBuf_7_V_2_fu_294;
wire   [7:0] inputBuf_7_V_21_fu_665_p3;
reg   [7:0] inputBuf_7_V_11_fu_298;
wire   [7:0] inputBuf_7_V_20_fu_657_p3;
reg   [7:0] inputBuf_7_V_9_fu_302;
wire   [7:0] inputBuf_7_V_18_fu_641_p3;
reg   [7:0] inputBuf_7_V_7_fu_306;
wire   [7:0] inputBuf_7_V_8_fu_625_p3;
reg   [7:0] inputBuf_7_V_5_fu_310;
wire   [7:0] inputBuf_7_V_6_fu_601_p3;
reg   [7:0] inputBuf_7_V_3_fu_314;
wire   [7:0] inputBuf_7_V_4_fu_585_p3;
reg   [7:0] inputBuf_7_V_14_fu_318;
wire   [7:0] inputBuf_7_V_1_fu_561_p3;
reg   [7:0] inputBuf_7_V_16_fu_322;
wire   [7:0] inputBuf_7_V_fu_537_p3;
reg    ap_block_pp0_stage0_01001;
wire   [2:0] inElem_V_fu_428_p9;
wire   [2:0] tmp_84_fu_451_p1;
wire   [0:0] sel_tmp6_fu_491_p2;
wire   [0:0] sel_tmp5_fu_485_p2;
wire   [0:0] sel_tmp4_fu_479_p2;
wire   [0:0] sel_tmp3_fu_473_p2;
wire   [0:0] sel_tmp2_fu_467_p2;
wire   [0:0] sel_tmp1_fu_461_p2;
wire   [0:0] sel_tmp_fu_455_p2;
wire   [0:0] or_cond_fu_497_p2;
wire   [0:0] or_cond1_fu_503_p2;
wire   [0:0] or_cond2_fu_509_p2;
wire   [7:0] newSel_fu_515_p3;
wire   [0:0] or_cond3_fu_523_p2;
wire   [7:0] newSel1_fu_529_p3;
wire   [7:0] newSel3_fu_545_p3;
wire   [7:0] newSel4_fu_553_p3;
wire   [7:0] newSel6_fu_569_p3;
wire   [7:0] newSel7_fu_577_p3;
wire   [7:0] newSel9_fu_593_p3;
wire   [7:0] newSel2_fu_609_p3;
wire   [7:0] newSel5_fu_617_p3;
wire   [7:0] newSel8_fu_633_p3;
wire   [7:0] inputBuf_7_V_19_fu_649_p3;
wire   [0:0] p_Result_2_fu_786_p3;
wire   [0:0] tmp_86_fu_722_p3;
wire   [0:0] tmp1_fu_794_p2;
wire   [0:0] tmp_83_fu_800_p2;
wire   [0:0] p_Result_2_0_1_fu_810_p3;
wire   [0:0] tmp_87_fu_730_p3;
wire   [0:0] tmp2_fu_818_p2;
wire   [0:0] tmp_16_0_1_fu_824_p2;
wire   [0:0] p_Result_2_0_2_fu_834_p3;
wire   [0:0] tmp_88_fu_738_p3;
wire   [0:0] tmp3_fu_842_p2;
wire   [0:0] tmp_16_0_2_fu_848_p2;
wire   [0:0] p_Result_2_0_3_fu_858_p3;
wire   [0:0] tmp_89_fu_746_p3;
wire   [0:0] tmp4_fu_866_p2;
wire   [0:0] tmp_16_0_3_fu_872_p2;
wire   [0:0] p_Result_2_0_4_fu_882_p3;
wire   [0:0] tmp_90_fu_754_p3;
wire   [0:0] tmp5_fu_890_p2;
wire   [0:0] p_Result_2_0_5_fu_902_p3;
wire   [0:0] tmp_91_fu_762_p3;
wire   [0:0] tmp6_fu_910_p2;
wire   [0:0] p_Result_2_0_6_fu_922_p3;
wire   [0:0] tmp_92_fu_770_p3;
wire   [0:0] tmp7_fu_930_p2;
wire   [0:0] p_Result_2_0_7_fu_942_p3;
wire   [0:0] tmp_93_fu_778_p3;
wire   [0:0] tmp8_fu_950_p2;
wire   [0:0] tmp_16_0_7_fu_956_p2;
wire   [1:0] res_cast_fu_806_p1;
wire   [1:0] res_0_3_cast_fu_878_p1;
wire   [1:0] tmp12_fu_966_p2;
wire   [1:0] res_0_7_cast_fu_962_p1;
wire   [1:0] res_0_1_cast_fu_830_p1;
wire   [1:0] res_0_2_cast_fu_854_p1;
wire   [1:0] tmp13_fu_976_p2;
wire   [1:0] tmp14_fu_982_p2;
wire   [2:0] tmp138_cast_fu_972_p1;
wire   [2:0] tmp139_cast_fu_988_p1;
wire   [0:0] tmp_94_fu_998_p3;
wire   [0:0] tmp16_fu_1062_p2;
wire   [0:0] tmp_16_1_fu_1068_p2;
wire   [0:0] tmp_95_fu_1006_p3;
wire   [0:0] tmp17_fu_1078_p2;
wire   [0:0] tmp_16_1_1_fu_1084_p2;
wire   [0:0] tmp_96_fu_1014_p3;
wire   [0:0] tmp18_fu_1094_p2;
wire   [0:0] tmp_16_1_2_fu_1100_p2;
wire   [0:0] tmp_97_fu_1022_p3;
wire   [0:0] tmp19_fu_1110_p2;
wire   [0:0] tmp_16_1_3_fu_1116_p2;
wire   [0:0] tmp_98_fu_1030_p3;
wire   [0:0] tmp20_fu_1126_p2;
wire   [0:0] tmp_99_fu_1038_p3;
wire   [0:0] tmp21_fu_1138_p2;
wire   [0:0] tmp_100_fu_1046_p3;
wire   [0:0] tmp22_fu_1150_p2;
wire   [0:0] tmp_101_fu_1054_p3;
wire   [0:0] tmp23_fu_1162_p2;
wire   [0:0] tmp_16_1_7_fu_1168_p2;
wire   [1:0] res_1_cast_fu_1074_p1;
wire   [1:0] res_1_3_cast_fu_1122_p1;
wire   [1:0] tmp27_fu_1178_p2;
wire   [1:0] res_1_7_cast_fu_1174_p1;
wire   [1:0] res_1_1_cast_fu_1090_p1;
wire   [1:0] res_1_2_cast_fu_1106_p1;
wire   [1:0] tmp28_fu_1188_p2;
wire   [1:0] tmp29_fu_1194_p2;
wire   [2:0] tmp159_cast_fu_1184_p1;
wire   [2:0] tmp160_cast_fu_1200_p1;
wire   [0:0] tmp_102_fu_1210_p3;
wire   [0:0] tmp31_fu_1274_p2;
wire   [0:0] tmp_16_2_fu_1280_p2;
wire   [0:0] tmp_103_fu_1218_p3;
wire   [0:0] tmp32_fu_1290_p2;
wire   [0:0] tmp_16_2_1_fu_1296_p2;
wire   [0:0] tmp_104_fu_1226_p3;
wire   [0:0] tmp33_fu_1306_p2;
wire   [0:0] tmp_16_2_2_fu_1312_p2;
wire   [0:0] tmp_105_fu_1234_p3;
wire   [0:0] tmp34_fu_1322_p2;
wire   [0:0] tmp_16_2_3_fu_1328_p2;
wire   [0:0] tmp_106_fu_1242_p3;
wire   [0:0] tmp35_fu_1338_p2;
wire   [0:0] tmp_107_fu_1250_p3;
wire   [0:0] tmp36_fu_1350_p2;
wire   [0:0] tmp_108_fu_1258_p3;
wire   [0:0] tmp37_fu_1362_p2;
wire   [0:0] tmp_109_fu_1266_p3;
wire   [0:0] tmp38_fu_1374_p2;
wire   [0:0] tmp_16_2_7_fu_1380_p2;
wire   [1:0] res_cast_59_fu_1286_p1;
wire   [1:0] res_218_3_cast_fu_1334_p1;
wire   [1:0] tmp42_fu_1390_p2;
wire   [1:0] res_218_7_cast_fu_1386_p1;
wire   [1:0] res_218_1_cast_fu_1302_p1;
wire   [1:0] res_218_2_cast_fu_1318_p1;
wire   [1:0] tmp43_fu_1400_p2;
wire   [1:0] tmp44_fu_1406_p2;
wire   [2:0] tmp180_cast_fu_1396_p1;
wire   [2:0] tmp181_cast_fu_1412_p1;
wire   [0:0] tmp_110_fu_1422_p3;
wire   [0:0] tmp46_fu_1486_p2;
wire   [0:0] tmp_16_3_fu_1492_p2;
wire   [0:0] tmp_111_fu_1430_p3;
wire   [0:0] tmp47_fu_1502_p2;
wire   [0:0] tmp_16_3_1_fu_1508_p2;
wire   [0:0] tmp_112_fu_1438_p3;
wire   [0:0] tmp48_fu_1518_p2;
wire   [0:0] tmp_16_3_2_fu_1524_p2;
wire   [0:0] tmp_113_fu_1446_p3;
wire   [0:0] tmp49_fu_1534_p2;
wire   [0:0] tmp_16_3_3_fu_1540_p2;
wire   [0:0] tmp_114_fu_1454_p3;
wire   [0:0] tmp50_fu_1550_p2;
wire   [0:0] tmp_115_fu_1462_p3;
wire   [0:0] tmp51_fu_1562_p2;
wire   [0:0] tmp_116_fu_1470_p3;
wire   [0:0] tmp52_fu_1574_p2;
wire   [0:0] tmp_117_fu_1478_p3;
wire   [0:0] tmp53_fu_1586_p2;
wire   [0:0] tmp_16_3_7_fu_1592_p2;
wire   [1:0] res_3_cast_fu_1498_p1;
wire   [1:0] res_3_3_cast_fu_1546_p1;
wire   [1:0] tmp57_fu_1602_p2;
wire   [1:0] res_3_7_cast_fu_1598_p1;
wire   [1:0] res_3_1_cast_fu_1514_p1;
wire   [1:0] res_3_2_cast_fu_1530_p1;
wire   [1:0] tmp58_fu_1612_p2;
wire   [1:0] tmp59_fu_1618_p2;
wire   [2:0] tmp201_cast_fu_1608_p1;
wire   [2:0] tmp202_cast_fu_1624_p1;
wire   [0:0] tmp_118_fu_1634_p3;
wire   [0:0] tmp61_fu_1698_p2;
wire   [0:0] tmp_16_4_fu_1704_p2;
wire   [0:0] tmp_119_fu_1642_p3;
wire   [0:0] tmp62_fu_1714_p2;
wire   [0:0] tmp_16_4_1_fu_1720_p2;
wire   [0:0] tmp_120_fu_1650_p3;
wire   [0:0] tmp63_fu_1730_p2;
wire   [0:0] tmp_16_4_2_fu_1736_p2;
wire   [0:0] tmp_121_fu_1658_p3;
wire   [0:0] tmp64_fu_1746_p2;
wire   [0:0] tmp_16_4_3_fu_1752_p2;
wire   [0:0] tmp_122_fu_1666_p3;
wire   [0:0] tmp65_fu_1762_p2;
wire   [0:0] tmp_123_fu_1674_p3;
wire   [0:0] tmp66_fu_1774_p2;
wire   [0:0] tmp_124_fu_1682_p3;
wire   [0:0] tmp67_fu_1786_p2;
wire   [0:0] tmp_125_fu_1690_p3;
wire   [0:0] tmp68_fu_1798_p2;
wire   [0:0] tmp_16_4_7_fu_1804_p2;
wire   [1:0] res_4_cast_fu_1710_p1;
wire   [1:0] res_4_3_cast_fu_1758_p1;
wire   [1:0] tmp72_fu_1814_p2;
wire   [1:0] res_4_7_cast_fu_1810_p1;
wire   [1:0] res_4_1_cast_fu_1726_p1;
wire   [1:0] res_4_2_cast_fu_1742_p1;
wire   [1:0] tmp73_fu_1824_p2;
wire   [1:0] tmp74_fu_1830_p2;
wire   [2:0] tmp222_cast_fu_1820_p1;
wire   [2:0] tmp223_cast_fu_1836_p1;
wire   [0:0] tmp_126_fu_1846_p3;
wire   [0:0] tmp76_fu_1910_p2;
wire   [0:0] tmp_16_5_fu_1916_p2;
wire   [0:0] tmp_127_fu_1854_p3;
wire   [0:0] tmp77_fu_1926_p2;
wire   [0:0] tmp_16_5_1_fu_1932_p2;
wire   [0:0] tmp_128_fu_1862_p3;
wire   [0:0] tmp78_fu_1942_p2;
wire   [0:0] tmp_16_5_2_fu_1948_p2;
wire   [0:0] tmp_129_fu_1870_p3;
wire   [0:0] tmp79_fu_1958_p2;
wire   [0:0] tmp_16_5_3_fu_1964_p2;
wire   [0:0] tmp_130_fu_1878_p3;
wire   [0:0] tmp80_fu_1974_p2;
wire   [0:0] tmp_131_fu_1886_p3;
wire   [0:0] tmp81_fu_1986_p2;
wire   [0:0] tmp_132_fu_1894_p3;
wire   [0:0] tmp82_fu_1998_p2;
wire   [0:0] tmp_133_fu_1902_p3;
wire   [0:0] tmp83_fu_2010_p2;
wire   [0:0] tmp_16_5_7_fu_2016_p2;
wire   [1:0] res_5_cast_fu_1922_p1;
wire   [1:0] res_5_3_cast_fu_1970_p1;
wire   [1:0] tmp87_fu_2026_p2;
wire   [1:0] res_5_7_cast_fu_2022_p1;
wire   [1:0] res_5_1_cast_fu_1938_p1;
wire   [1:0] res_5_2_cast_fu_1954_p1;
wire   [1:0] tmp88_fu_2036_p2;
wire   [1:0] tmp89_fu_2042_p2;
wire   [2:0] tmp243_cast_fu_2032_p1;
wire   [2:0] tmp244_cast_fu_2048_p1;
wire   [0:0] tmp_134_fu_2058_p3;
wire   [0:0] tmp91_fu_2122_p2;
wire   [0:0] tmp_16_6_fu_2128_p2;
wire   [0:0] tmp_135_fu_2066_p3;
wire   [0:0] tmp92_fu_2138_p2;
wire   [0:0] tmp_16_6_1_fu_2144_p2;
wire   [0:0] tmp_136_fu_2074_p3;
wire   [0:0] tmp93_fu_2154_p2;
wire   [0:0] tmp_16_6_2_fu_2160_p2;
wire   [0:0] tmp_137_fu_2082_p3;
wire   [0:0] tmp94_fu_2170_p2;
wire   [0:0] tmp_16_6_3_fu_2176_p2;
wire   [0:0] tmp_138_fu_2090_p3;
wire   [0:0] tmp95_fu_2186_p2;
wire   [0:0] tmp_139_fu_2098_p3;
wire   [0:0] tmp96_fu_2198_p2;
wire   [0:0] tmp_140_fu_2106_p3;
wire   [0:0] tmp97_fu_2210_p2;
wire   [0:0] tmp_141_fu_2114_p3;
wire   [0:0] tmp98_fu_2222_p2;
wire   [0:0] tmp_16_6_7_fu_2228_p2;
wire   [1:0] res_6_cast_fu_2134_p1;
wire   [1:0] res_6_3_cast_fu_2182_p1;
wire   [1:0] tmp102_fu_2238_p2;
wire   [1:0] res_6_7_cast_fu_2234_p1;
wire   [1:0] res_6_1_cast_fu_2150_p1;
wire   [1:0] res_6_2_cast_fu_2166_p1;
wire   [1:0] tmp103_fu_2248_p2;
wire   [1:0] tmp104_fu_2254_p2;
wire   [2:0] tmp264_cast_fu_2244_p1;
wire   [2:0] tmp265_cast_fu_2260_p1;
wire   [0:0] tmp_142_fu_2270_p3;
wire   [0:0] tmp106_fu_2334_p2;
wire   [0:0] tmp_16_7_fu_2340_p2;
wire   [0:0] tmp_143_fu_2278_p3;
wire   [0:0] tmp107_fu_2350_p2;
wire   [0:0] tmp_16_7_1_fu_2356_p2;
wire   [0:0] tmp_144_fu_2286_p3;
wire   [0:0] tmp108_fu_2366_p2;
wire   [0:0] tmp_16_7_2_fu_2372_p2;
wire   [0:0] tmp_145_fu_2294_p3;
wire   [0:0] tmp109_fu_2382_p2;
wire   [0:0] tmp_16_7_3_fu_2388_p2;
wire   [0:0] tmp_146_fu_2302_p3;
wire   [0:0] tmp110_fu_2398_p2;
wire   [0:0] tmp_147_fu_2310_p3;
wire   [0:0] tmp111_fu_2410_p2;
wire   [0:0] tmp_148_fu_2318_p3;
wire   [0:0] tmp112_fu_2422_p2;
wire   [0:0] tmp_149_fu_2326_p3;
wire   [0:0] tmp113_fu_2434_p2;
wire   [0:0] tmp_16_7_7_fu_2440_p2;
wire   [1:0] res_7_cast_fu_2346_p1;
wire   [1:0] res_7_3_cast_fu_2394_p1;
wire   [1:0] tmp117_fu_2450_p2;
wire   [1:0] res_7_7_cast_fu_2446_p1;
wire   [1:0] res_7_1_cast_fu_2362_p1;
wire   [1:0] res_7_2_cast_fu_2378_p1;
wire   [1:0] tmp118_fu_2460_p2;
wire   [1:0] tmp119_fu_2466_p2;
wire   [2:0] tmp285_cast_fu_2456_p1;
wire   [2:0] tmp286_cast_fu_2472_p1;
wire   [0:0] tmp_150_fu_2482_p3;
wire   [0:0] tmp121_fu_2546_p2;
wire   [0:0] tmp_16_8_fu_2552_p2;
wire   [0:0] tmp_151_fu_2490_p3;
wire   [0:0] tmp122_fu_2562_p2;
wire   [0:0] tmp_16_8_1_fu_2568_p2;
wire   [0:0] tmp_152_fu_2498_p3;
wire   [0:0] tmp123_fu_2578_p2;
wire   [0:0] tmp_16_8_2_fu_2584_p2;
wire   [0:0] tmp_153_fu_2506_p3;
wire   [0:0] tmp124_fu_2594_p2;
wire   [0:0] tmp_16_8_3_fu_2600_p2;
wire   [0:0] tmp_154_fu_2514_p3;
wire   [0:0] tmp125_fu_2610_p2;
wire   [0:0] tmp_155_fu_2522_p3;
wire   [0:0] tmp126_fu_2622_p2;
wire   [0:0] tmp_156_fu_2530_p3;
wire   [0:0] tmp127_fu_2634_p2;
wire   [0:0] tmp_157_fu_2538_p3;
wire   [0:0] tmp128_fu_2646_p2;
wire   [0:0] tmp_16_8_7_fu_2652_p2;
wire   [1:0] res_8_cast_fu_2558_p1;
wire   [1:0] res_8_3_cast_fu_2606_p1;
wire   [1:0] tmp132_fu_2662_p2;
wire   [1:0] res_8_7_cast_fu_2658_p1;
wire   [1:0] res_8_1_cast_fu_2574_p1;
wire   [1:0] res_8_2_cast_fu_2590_p1;
wire   [1:0] tmp133_fu_2672_p2;
wire   [1:0] tmp134_fu_2678_p2;
wire   [2:0] tmp306_cast_fu_2668_p1;
wire   [2:0] tmp307_cast_fu_2684_p1;
wire   [0:0] tmp_158_fu_2694_p1;
wire   [0:0] tmp136_fu_2754_p2;
wire   [0:0] tmp_16_9_fu_2760_p2;
wire   [0:0] tmp_159_fu_2698_p3;
wire   [0:0] tmp137_fu_2770_p2;
wire   [0:0] tmp_16_9_1_fu_2776_p2;
wire   [0:0] tmp_160_fu_2706_p3;
wire   [0:0] tmp138_fu_2786_p2;
wire   [0:0] tmp_16_9_2_fu_2792_p2;
wire   [0:0] tmp_161_fu_2714_p3;
wire   [0:0] tmp139_fu_2802_p2;
wire   [0:0] tmp_16_9_3_fu_2808_p2;
wire   [0:0] tmp_162_fu_2722_p3;
wire   [0:0] tmp140_fu_2818_p2;
wire   [0:0] tmp_163_fu_2730_p3;
wire   [0:0] tmp141_fu_2830_p2;
wire   [0:0] tmp_164_fu_2738_p3;
wire   [0:0] tmp142_fu_2842_p2;
wire   [0:0] tmp_165_fu_2746_p3;
wire   [0:0] tmp143_fu_2854_p2;
wire   [0:0] tmp_16_9_7_fu_2860_p2;
wire   [1:0] res_9_cast_fu_2766_p1;
wire   [1:0] res_9_3_cast_fu_2814_p1;
wire   [1:0] tmp147_fu_2870_p2;
wire   [1:0] res_9_7_cast_fu_2866_p1;
wire   [1:0] res_9_1_cast_fu_2782_p1;
wire   [1:0] res_9_2_cast_fu_2798_p1;
wire   [1:0] tmp148_fu_2880_p2;
wire   [1:0] tmp149_fu_2886_p2;
wire   [2:0] tmp327_cast_fu_2876_p1;
wire   [2:0] tmp328_cast_fu_2892_p1;
wire   [31:0] nf_1_fu_2922_p2;
wire   [31:0] res_0_5_fu_3044_p1;
wire   [31:0] p_accu_V_fu_3034_p3;
wire   [1:0] res_0_4_cast_fu_3041_p1;
wire   [1:0] res_0_6_cast_fu_3047_p1;
wire   [1:0] tmp10_fu_3056_p2;
wire   [31:0] tmp9_fu_3050_p2;
wire   [31:0] tmp136_cast_fu_3062_p1;
wire   [31:0] tmp11_fu_3066_p2;
wire   [31:0] tmp137_cast_fu_3072_p1;
wire   [31:0] res_1_5_fu_3084_p1;
wire   [31:0] p_accu_V_0_1_fu_3027_p3;
wire   [1:0] res_1_4_cast_fu_3081_p1;
wire   [1:0] res_1_6_cast_fu_3087_p1;
wire   [1:0] tmp25_fu_3096_p2;
wire   [31:0] tmp24_fu_3090_p2;
wire   [31:0] tmp157_cast_fu_3102_p1;
wire   [31:0] tmp26_fu_3106_p2;
wire   [31:0] tmp158_cast_fu_3112_p1;
wire   [31:0] res_218_5_fu_3124_p1;
wire   [31:0] p_accu_V_0_2_fu_3020_p3;
wire   [1:0] res_218_4_cast_fu_3121_p1;
wire   [1:0] res_218_6_cast_fu_3127_p1;
wire   [1:0] tmp40_fu_3136_p2;
wire   [31:0] tmp39_fu_3130_p2;
wire   [31:0] tmp178_cast_fu_3142_p1;
wire   [31:0] tmp41_fu_3146_p2;
wire   [31:0] tmp179_cast_fu_3152_p1;
wire   [31:0] res_3_5_fu_3164_p1;
wire   [31:0] p_accu_V_0_3_fu_3013_p3;
wire   [1:0] res_3_4_cast_fu_3161_p1;
wire   [1:0] res_3_6_cast_fu_3167_p1;
wire   [1:0] tmp55_fu_3176_p2;
wire   [31:0] tmp54_fu_3170_p2;
wire   [31:0] tmp199_cast_fu_3182_p1;
wire   [31:0] tmp56_fu_3186_p2;
wire   [31:0] tmp200_cast_fu_3192_p1;
wire   [31:0] res_4_5_fu_3204_p1;
wire   [31:0] p_accu_V_0_4_fu_3006_p3;
wire   [1:0] res_4_4_cast_fu_3201_p1;
wire   [1:0] res_4_6_cast_fu_3207_p1;
wire   [1:0] tmp70_fu_3216_p2;
wire   [31:0] tmp69_fu_3210_p2;
wire   [31:0] tmp220_cast_fu_3222_p1;
wire   [31:0] tmp71_fu_3226_p2;
wire   [31:0] tmp221_cast_fu_3232_p1;
wire   [31:0] res_5_5_fu_3244_p1;
wire   [31:0] p_accu_V_0_5_fu_2999_p3;
wire   [1:0] res_5_4_cast_fu_3241_p1;
wire   [1:0] res_5_6_cast_fu_3247_p1;
wire   [1:0] tmp85_fu_3256_p2;
wire   [31:0] tmp84_fu_3250_p2;
wire   [31:0] tmp241_cast_fu_3262_p1;
wire   [31:0] tmp86_fu_3266_p2;
wire   [31:0] tmp242_cast_fu_3272_p1;
wire   [31:0] res_6_5_fu_3284_p1;
wire   [31:0] p_accu_V_0_6_fu_2992_p3;
wire   [1:0] res_6_4_cast_fu_3281_p1;
wire   [1:0] res_6_6_cast_fu_3287_p1;
wire   [1:0] tmp100_fu_3296_p2;
wire   [31:0] tmp99_fu_3290_p2;
wire   [31:0] tmp262_cast_fu_3302_p1;
wire   [31:0] tmp101_fu_3306_p2;
wire   [31:0] tmp263_cast_fu_3312_p1;
wire   [31:0] res_7_5_fu_3324_p1;
wire   [31:0] p_accu_V_0_7_fu_2985_p3;
wire   [1:0] res_7_4_cast_fu_3321_p1;
wire   [1:0] res_7_6_cast_fu_3327_p1;
wire   [1:0] tmp115_fu_3336_p2;
wire   [31:0] tmp114_fu_3330_p2;
wire   [31:0] tmp283_cast_fu_3342_p1;
wire   [31:0] tmp116_fu_3346_p2;
wire   [31:0] tmp284_cast_fu_3352_p1;
wire   [31:0] res_8_5_fu_3364_p1;
wire   [31:0] p_accu_V_0_8_fu_2978_p3;
wire   [1:0] res_8_4_cast_fu_3361_p1;
wire   [1:0] res_8_6_cast_fu_3367_p1;
wire   [1:0] tmp130_fu_3376_p2;
wire   [31:0] tmp129_fu_3370_p2;
wire   [31:0] tmp304_cast_fu_3382_p1;
wire   [31:0] tmp131_fu_3386_p2;
wire   [31:0] tmp305_cast_fu_3392_p1;
wire   [31:0] res_9_5_fu_3404_p1;
wire   [31:0] p_accu_V_0_9_fu_2971_p3;
wire   [1:0] res_9_4_cast_fu_3401_p1;
wire   [1:0] res_9_6_cast_fu_3407_p1;
wire   [1:0] tmp145_fu_3416_p2;
wire   [31:0] tmp144_fu_3410_p2;
wire   [31:0] tmp325_cast_fu_3422_p1;
wire   [31:0] tmp146_fu_3426_p2;
wire   [31:0] tmp326_cast_fu_3432_p1;
wire    ap_CS_fsm_state4;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_63;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3_mux_83_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
StreamingFCLayer_Batch_3_mux_83_8_1_1_U1(
    .din0(inputBuf_7_V_2_fu_294),
    .din1(inputBuf_7_V_11_fu_298),
    .din2(inputBuf_7_V_9_fu_302),
    .din3(inputBuf_7_V_7_fu_306),
    .din4(inputBuf_7_V_5_fu_310),
    .din5(inputBuf_7_V_3_fu_314),
    .din6(inputBuf_7_V_14_fu_318),
    .din7(inputBuf_7_V_16_fu_322),
    .din8(inElem_V_fu_428_p9),
    .dout(inElem_V_fu_428_p10)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_345 <= i_1_fu_382_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_345 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_9_fu_2908_p2 == 1'd1) & (exitcond_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nf_fu_290 <= p_s_fu_2928_p3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        nf_fu_290 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_9_fu_2908_p2 == 1'd0) & (exitcond_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sf_fu_286 <= sf_1_fu_2902_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (tmp_9_fu_2908_p2 == 1'd1) & (exitcond_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sf_fu_286 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        accu_0_0_V_1_fu_246 <= accu_0_0_V_fu_3075_p2;
        accu_0_1_V_1_fu_250 <= accu_0_1_V_fu_3115_p2;
        accu_0_2_V_1_fu_254 <= accu_0_2_V_fu_3155_p2;
        accu_0_3_V_1_fu_258 <= accu_0_3_V_fu_3195_p2;
        accu_0_4_V_1_fu_262 <= accu_0_4_V_fu_3235_p2;
        accu_0_5_V_1_fu_266 <= accu_0_5_V_fu_3275_p2;
        accu_0_6_V_1_fu_270 <= accu_0_6_V_fu_3315_p2;
        accu_0_7_V_1_fu_274 <= accu_0_7_V_fu_3355_p2;
        accu_0_8_V_1_fu_278 <= accu_0_8_V_fu_3395_p2;
        accu_0_9_V_1_fu_282 <= accu_0_9_V_fu_3435_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_fu_391_p2 == 1'd1) & (exitcond_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inputBuf_7_V_11_fu_298 <= inputBuf_7_V_20_fu_657_p3;
        inputBuf_7_V_14_fu_318 <= inputBuf_7_V_1_fu_561_p3;
        inputBuf_7_V_16_fu_322 <= inputBuf_7_V_fu_537_p3;
        inputBuf_7_V_2_fu_294 <= inputBuf_7_V_21_fu_665_p3;
        inputBuf_7_V_3_fu_314 <= inputBuf_7_V_4_fu_585_p3;
        inputBuf_7_V_5_fu_310 <= inputBuf_7_V_6_fu_601_p3;
        inputBuf_7_V_7_fu_306 <= inputBuf_7_V_8_fu_625_p3;
        inputBuf_7_V_9_fu_302 <= inputBuf_7_V_18_fu_641_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_fu_376_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp105_reg_3802 <= tmp105_fu_2264_p2;
        tmp120_reg_3822 <= tmp120_fu_2476_p2;
        tmp135_reg_3842 <= tmp135_fu_2688_p2;
        tmp150_reg_3862 <= tmp150_fu_2896_p2;
        tmp15_reg_3682 <= tmp15_fu_992_p2;
        tmp30_reg_3702 <= tmp30_fu_1204_p2;
        tmp45_reg_3722 <= tmp45_fu_1416_p2;
        tmp60_reg_3742 <= tmp60_fu_1628_p2;
        tmp75_reg_3762 <= tmp75_fu_1840_p2;
        tmp90_reg_3782 <= tmp90_fu_2052_p2;
        tmp_16_0_4_reg_3667 <= tmp_16_0_4_fu_896_p2;
        tmp_16_0_5_reg_3672 <= tmp_16_0_5_fu_916_p2;
        tmp_16_0_6_reg_3677 <= tmp_16_0_6_fu_936_p2;
        tmp_16_1_4_reg_3687 <= tmp_16_1_4_fu_1132_p2;
        tmp_16_1_5_reg_3692 <= tmp_16_1_5_fu_1144_p2;
        tmp_16_1_6_reg_3697 <= tmp_16_1_6_fu_1156_p2;
        tmp_16_2_4_reg_3707 <= tmp_16_2_4_fu_1344_p2;
        tmp_16_2_5_reg_3712 <= tmp_16_2_5_fu_1356_p2;
        tmp_16_2_6_reg_3717 <= tmp_16_2_6_fu_1368_p2;
        tmp_16_3_4_reg_3727 <= tmp_16_3_4_fu_1556_p2;
        tmp_16_3_5_reg_3732 <= tmp_16_3_5_fu_1568_p2;
        tmp_16_3_6_reg_3737 <= tmp_16_3_6_fu_1580_p2;
        tmp_16_4_4_reg_3747 <= tmp_16_4_4_fu_1768_p2;
        tmp_16_4_5_reg_3752 <= tmp_16_4_5_fu_1780_p2;
        tmp_16_4_6_reg_3757 <= tmp_16_4_6_fu_1792_p2;
        tmp_16_5_4_reg_3767 <= tmp_16_5_4_fu_1980_p2;
        tmp_16_5_5_reg_3772 <= tmp_16_5_5_fu_1992_p2;
        tmp_16_5_6_reg_3777 <= tmp_16_5_6_fu_2004_p2;
        tmp_16_6_4_reg_3787 <= tmp_16_6_4_fu_2192_p2;
        tmp_16_6_5_reg_3792 <= tmp_16_6_5_fu_2204_p2;
        tmp_16_6_6_reg_3797 <= tmp_16_6_6_fu_2216_p2;
        tmp_16_7_4_reg_3807 <= tmp_16_7_4_fu_2404_p2;
        tmp_16_7_5_reg_3812 <= tmp_16_7_5_fu_2416_p2;
        tmp_16_7_6_reg_3817 <= tmp_16_7_6_fu_2428_p2;
        tmp_16_8_4_reg_3827 <= tmp_16_8_4_fu_2616_p2;
        tmp_16_8_5_reg_3832 <= tmp_16_8_5_fu_2628_p2;
        tmp_16_8_6_reg_3837 <= tmp_16_8_6_fu_2640_p2;
        tmp_16_9_4_reg_3847 <= tmp_16_9_4_fu_2824_p2;
        tmp_16_9_5_reg_3852 <= tmp_16_9_5_fu_2836_p2;
        tmp_16_9_6_reg_3857 <= tmp_16_9_6_fu_2848_p2;
        tmp_6_reg_3653 <= tmp_6_fu_716_p2;
        tmp_9_reg_3867 <= tmp_9_fu_2908_p2;
    end
end

always @ (*) begin
    if ((exitcond_fu_376_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_63)) begin
        if ((tmp_fu_391_p2 == 1'd0)) begin
            ap_phi_mux_act_m_val_V_phi_fu_359_p4 = inElem_V_fu_428_p10;
        end else if ((tmp_fu_391_p2 == 1'd1)) begin
            ap_phi_mux_act_m_val_V_phi_fu_359_p4 = in_V_V_TDATA;
        end else begin
            ap_phi_mux_act_m_val_V_phi_fu_359_p4 = ap_phi_reg_pp0_iter0_act_m_val_V_reg_356;
        end
    end else begin
        ap_phi_mux_act_m_val_V_phi_fu_359_p4 = ap_phi_reg_pp0_iter0_act_m_val_V_reg_356;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_391_p2 == 1'd1) & (exitcond_fu_376_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_V_V_TDATA_blk_n = in_V_V_TVALID;
    end else begin
        in_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op53_read_state2 == 1'b1))) begin
        in_V_V_TREADY = 1'b1;
    end else begin
        in_V_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_9_reg_3867 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_V_V_TDATA_blk_n = out_V_V_TREADY;
    end else begin
        out_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_9_reg_3867 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_V_V_TVALID = 1'b1;
    end else begin
        out_V_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_fu_376_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weight_V_V_TDATA_blk_n = weight_V_V_TVALID;
    end else begin
        weight_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weight_V_V_TREADY = 1'b1;
    end else begin
        weight_V_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((exitcond_fu_376_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((exitcond_fu_376_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign accu_0_0_V_fu_3075_p2 = (tmp11_fu_3066_p2 + tmp137_cast_fu_3072_p1);

assign accu_0_1_V_fu_3115_p2 = (tmp26_fu_3106_p2 + tmp158_cast_fu_3112_p1);

assign accu_0_2_V_fu_3155_p2 = (tmp41_fu_3146_p2 + tmp179_cast_fu_3152_p1);

assign accu_0_3_V_fu_3195_p2 = (tmp56_fu_3186_p2 + tmp200_cast_fu_3192_p1);

assign accu_0_4_V_fu_3235_p2 = (tmp71_fu_3226_p2 + tmp221_cast_fu_3232_p1);

assign accu_0_5_V_fu_3275_p2 = (tmp86_fu_3266_p2 + tmp242_cast_fu_3272_p1);

assign accu_0_6_V_fu_3315_p2 = (tmp101_fu_3306_p2 + tmp263_cast_fu_3312_p1);

assign accu_0_7_V_fu_3355_p2 = (tmp116_fu_3346_p2 + tmp284_cast_fu_3352_p1);

assign accu_0_8_V_fu_3395_p2 = (tmp131_fu_3386_p2 + tmp305_cast_fu_3392_p1);

assign accu_0_9_V_fu_3435_p2 = (tmp146_fu_3426_p2 + tmp326_cast_fu_3432_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((in_V_V_TVALID == 1'b0) & (ap_predicate_op53_read_state2 == 1'b1)) | ((exitcond_fu_376_p2 == 1'd0) & (weight_V_V_TVALID == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_io)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (((in_V_V_TVALID == 1'b0) & (ap_predicate_op53_read_state2 == 1'b1)) | ((exitcond_fu_376_p2 == 1'd0) & (weight_V_V_TVALID == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_io)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (((in_V_V_TVALID == 1'b0) & (ap_predicate_op53_read_state2 == 1'b1)) | ((exitcond_fu_376_p2 == 1'd0) & (weight_V_V_TVALID == 1'b0)))));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = (((in_V_V_TVALID == 1'b0) & (ap_predicate_op53_read_state2 == 1'b1)) | ((exitcond_fu_376_p2 == 1'd0) & (weight_V_V_TVALID == 1'b0)));
end

always @ (*) begin
    ap_block_state3_io = ((tmp_9_reg_3867 == 1'd1) & (out_V_V_TREADY == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_63 = ((exitcond_fu_376_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_act_m_val_V_reg_356 = 'bx;

always @ (*) begin
    ap_predicate_op53_read_state2 = ((tmp_fu_391_p2 == 1'd1) & (exitcond_fu_376_p2 == 1'd0));
end

assign exitcond_fu_376_p2 = ((i_reg_345 == 4'd8) ? 1'b1 : 1'b0);

assign i_1_fu_382_p2 = (i_reg_345 + 4'd1);

assign inElem_V_fu_428_p9 = sf_fu_286[2:0];

assign inputBuf_7_V_18_fu_641_p3 = ((or_cond_fu_497_p2[0:0] === 1'b1) ? inputBuf_7_V_9_fu_302 : newSel8_fu_633_p3);

assign inputBuf_7_V_19_fu_649_p3 = ((sel_tmp5_fu_485_p2[0:0] === 1'b1) ? in_V_V_TDATA : inputBuf_7_V_11_fu_298);

assign inputBuf_7_V_1_fu_561_p3 = ((or_cond3_fu_523_p2[0:0] === 1'b1) ? inputBuf_7_V_14_fu_318 : newSel4_fu_553_p3);

assign inputBuf_7_V_20_fu_657_p3 = ((sel_tmp6_fu_491_p2[0:0] === 1'b1) ? inputBuf_7_V_11_fu_298 : inputBuf_7_V_19_fu_649_p3);

assign inputBuf_7_V_21_fu_665_p3 = ((sel_tmp6_fu_491_p2[0:0] === 1'b1) ? in_V_V_TDATA : inputBuf_7_V_2_fu_294);

assign inputBuf_7_V_4_fu_585_p3 = ((or_cond3_fu_523_p2[0:0] === 1'b1) ? inputBuf_7_V_3_fu_314 : newSel7_fu_577_p3);

assign inputBuf_7_V_6_fu_601_p3 = ((or_cond3_fu_523_p2[0:0] === 1'b1) ? inputBuf_7_V_5_fu_310 : newSel9_fu_593_p3);

assign inputBuf_7_V_8_fu_625_p3 = ((or_cond3_fu_523_p2[0:0] === 1'b1) ? newSel5_fu_617_p3 : inputBuf_7_V_7_fu_306);

assign inputBuf_7_V_fu_537_p3 = ((or_cond3_fu_523_p2[0:0] === 1'b1) ? inputBuf_7_V_16_fu_322 : newSel1_fu_529_p3);

assign newSel1_fu_529_p3 = ((or_cond2_fu_509_p2[0:0] === 1'b1) ? inputBuf_7_V_16_fu_322 : newSel_fu_515_p3);

assign newSel2_fu_609_p3 = ((sel_tmp4_fu_479_p2[0:0] === 1'b1) ? inputBuf_7_V_7_fu_306 : in_V_V_TDATA);

assign newSel3_fu_545_p3 = ((sel_tmp_fu_455_p2[0:0] === 1'b1) ? in_V_V_TDATA : inputBuf_7_V_14_fu_318);

assign newSel4_fu_553_p3 = ((or_cond2_fu_509_p2[0:0] === 1'b1) ? inputBuf_7_V_14_fu_318 : newSel3_fu_545_p3);

assign newSel5_fu_617_p3 = ((or_cond_fu_497_p2[0:0] === 1'b1) ? inputBuf_7_V_7_fu_306 : newSel2_fu_609_p3);

assign newSel6_fu_569_p3 = ((sel_tmp2_fu_467_p2[0:0] === 1'b1) ? inputBuf_7_V_3_fu_314 : in_V_V_TDATA);

assign newSel7_fu_577_p3 = ((or_cond2_fu_509_p2[0:0] === 1'b1) ? newSel6_fu_569_p3 : inputBuf_7_V_3_fu_314);

assign newSel8_fu_633_p3 = ((sel_tmp4_fu_479_p2[0:0] === 1'b1) ? in_V_V_TDATA : inputBuf_7_V_9_fu_302);

assign newSel9_fu_593_p3 = ((sel_tmp2_fu_467_p2[0:0] === 1'b1) ? in_V_V_TDATA : inputBuf_7_V_5_fu_310);

assign newSel_fu_515_p3 = ((sel_tmp_fu_455_p2[0:0] === 1'b1) ? inputBuf_7_V_16_fu_322 : in_V_V_TDATA);

assign nf_1_fu_2922_p2 = (nf_fu_290 + 32'd1);

assign or_cond1_fu_503_p2 = (sel_tmp4_fu_479_p2 | sel_tmp3_fu_473_p2);

assign or_cond2_fu_509_p2 = (sel_tmp2_fu_467_p2 | sel_tmp1_fu_461_p2);

assign or_cond3_fu_523_p2 = (or_cond_fu_497_p2 | or_cond1_fu_503_p2);

assign or_cond_fu_497_p2 = (sel_tmp6_fu_491_p2 | sel_tmp5_fu_485_p2);

assign out_V_V_TDATA = {{{{{{{{{{accu_0_9_V_fu_3435_p2}, {accu_0_8_V_fu_3395_p2}}, {accu_0_7_V_fu_3355_p2}}, {accu_0_6_V_fu_3315_p2}}, {accu_0_5_V_fu_3275_p2}}, {accu_0_4_V_fu_3235_p2}}, {accu_0_3_V_fu_3195_p2}}, {accu_0_2_V_fu_3155_p2}}, {accu_0_1_V_fu_3115_p2}}, {accu_0_0_V_fu_3075_p2}};

assign p_Result_2_0_1_fu_810_p3 = ap_phi_mux_act_m_val_V_phi_fu_359_p4[8'd1];

assign p_Result_2_0_2_fu_834_p3 = ap_phi_mux_act_m_val_V_phi_fu_359_p4[8'd2];

assign p_Result_2_0_3_fu_858_p3 = ap_phi_mux_act_m_val_V_phi_fu_359_p4[8'd3];

assign p_Result_2_0_4_fu_882_p3 = ap_phi_mux_act_m_val_V_phi_fu_359_p4[8'd4];

assign p_Result_2_0_5_fu_902_p3 = ap_phi_mux_act_m_val_V_phi_fu_359_p4[8'd5];

assign p_Result_2_0_6_fu_922_p3 = ap_phi_mux_act_m_val_V_phi_fu_359_p4[8'd6];

assign p_Result_2_0_7_fu_942_p3 = ap_phi_mux_act_m_val_V_phi_fu_359_p4[8'd7];

assign p_Result_2_fu_786_p3 = ap_phi_mux_act_m_val_V_phi_fu_359_p4[8'd0];

assign p_accu_V_0_1_fu_3027_p3 = ((tmp_6_reg_3653[0:0] === 1'b1) ? 32'd0 : accu_0_1_V_1_fu_250);

assign p_accu_V_0_2_fu_3020_p3 = ((tmp_6_reg_3653[0:0] === 1'b1) ? 32'd0 : accu_0_2_V_1_fu_254);

assign p_accu_V_0_3_fu_3013_p3 = ((tmp_6_reg_3653[0:0] === 1'b1) ? 32'd0 : accu_0_3_V_1_fu_258);

assign p_accu_V_0_4_fu_3006_p3 = ((tmp_6_reg_3653[0:0] === 1'b1) ? 32'd0 : accu_0_4_V_1_fu_262);

assign p_accu_V_0_5_fu_2999_p3 = ((tmp_6_reg_3653[0:0] === 1'b1) ? 32'd0 : accu_0_5_V_1_fu_266);

assign p_accu_V_0_6_fu_2992_p3 = ((tmp_6_reg_3653[0:0] === 1'b1) ? 32'd0 : accu_0_6_V_1_fu_270);

assign p_accu_V_0_7_fu_2985_p3 = ((tmp_6_reg_3653[0:0] === 1'b1) ? 32'd0 : accu_0_7_V_1_fu_274);

assign p_accu_V_0_8_fu_2978_p3 = ((tmp_6_reg_3653[0:0] === 1'b1) ? 32'd0 : accu_0_8_V_1_fu_278);

assign p_accu_V_0_9_fu_2971_p3 = ((tmp_6_reg_3653[0:0] === 1'b1) ? 32'd0 : accu_0_9_V_1_fu_282);

assign p_accu_V_fu_3034_p3 = ((tmp_6_reg_3653[0:0] === 1'b1) ? 32'd0 : accu_0_0_V_1_fu_246);

assign p_s_fu_2928_p3 = ((tmp_fu_391_p2[0:0] === 1'b1) ? 32'd0 : nf_1_fu_2922_p2);

assign res_0_1_cast_fu_830_p1 = tmp_16_0_1_fu_824_p2;

assign res_0_2_cast_fu_854_p1 = tmp_16_0_2_fu_848_p2;

assign res_0_3_cast_fu_878_p1 = tmp_16_0_3_fu_872_p2;

assign res_0_4_cast_fu_3041_p1 = tmp_16_0_4_reg_3667;

assign res_0_5_fu_3044_p1 = tmp_16_0_5_reg_3672;

assign res_0_6_cast_fu_3047_p1 = tmp_16_0_6_reg_3677;

assign res_0_7_cast_fu_962_p1 = tmp_16_0_7_fu_956_p2;

assign res_1_1_cast_fu_1090_p1 = tmp_16_1_1_fu_1084_p2;

assign res_1_2_cast_fu_1106_p1 = tmp_16_1_2_fu_1100_p2;

assign res_1_3_cast_fu_1122_p1 = tmp_16_1_3_fu_1116_p2;

assign res_1_4_cast_fu_3081_p1 = tmp_16_1_4_reg_3687;

assign res_1_5_fu_3084_p1 = tmp_16_1_5_reg_3692;

assign res_1_6_cast_fu_3087_p1 = tmp_16_1_6_reg_3697;

assign res_1_7_cast_fu_1174_p1 = tmp_16_1_7_fu_1168_p2;

assign res_1_cast_fu_1074_p1 = tmp_16_1_fu_1068_p2;

assign res_218_1_cast_fu_1302_p1 = tmp_16_2_1_fu_1296_p2;

assign res_218_2_cast_fu_1318_p1 = tmp_16_2_2_fu_1312_p2;

assign res_218_3_cast_fu_1334_p1 = tmp_16_2_3_fu_1328_p2;

assign res_218_4_cast_fu_3121_p1 = tmp_16_2_4_reg_3707;

assign res_218_5_fu_3124_p1 = tmp_16_2_5_reg_3712;

assign res_218_6_cast_fu_3127_p1 = tmp_16_2_6_reg_3717;

assign res_218_7_cast_fu_1386_p1 = tmp_16_2_7_fu_1380_p2;

assign res_3_1_cast_fu_1514_p1 = tmp_16_3_1_fu_1508_p2;

assign res_3_2_cast_fu_1530_p1 = tmp_16_3_2_fu_1524_p2;

assign res_3_3_cast_fu_1546_p1 = tmp_16_3_3_fu_1540_p2;

assign res_3_4_cast_fu_3161_p1 = tmp_16_3_4_reg_3727;

assign res_3_5_fu_3164_p1 = tmp_16_3_5_reg_3732;

assign res_3_6_cast_fu_3167_p1 = tmp_16_3_6_reg_3737;

assign res_3_7_cast_fu_1598_p1 = tmp_16_3_7_fu_1592_p2;

assign res_3_cast_fu_1498_p1 = tmp_16_3_fu_1492_p2;

assign res_4_1_cast_fu_1726_p1 = tmp_16_4_1_fu_1720_p2;

assign res_4_2_cast_fu_1742_p1 = tmp_16_4_2_fu_1736_p2;

assign res_4_3_cast_fu_1758_p1 = tmp_16_4_3_fu_1752_p2;

assign res_4_4_cast_fu_3201_p1 = tmp_16_4_4_reg_3747;

assign res_4_5_fu_3204_p1 = tmp_16_4_5_reg_3752;

assign res_4_6_cast_fu_3207_p1 = tmp_16_4_6_reg_3757;

assign res_4_7_cast_fu_1810_p1 = tmp_16_4_7_fu_1804_p2;

assign res_4_cast_fu_1710_p1 = tmp_16_4_fu_1704_p2;

assign res_5_1_cast_fu_1938_p1 = tmp_16_5_1_fu_1932_p2;

assign res_5_2_cast_fu_1954_p1 = tmp_16_5_2_fu_1948_p2;

assign res_5_3_cast_fu_1970_p1 = tmp_16_5_3_fu_1964_p2;

assign res_5_4_cast_fu_3241_p1 = tmp_16_5_4_reg_3767;

assign res_5_5_fu_3244_p1 = tmp_16_5_5_reg_3772;

assign res_5_6_cast_fu_3247_p1 = tmp_16_5_6_reg_3777;

assign res_5_7_cast_fu_2022_p1 = tmp_16_5_7_fu_2016_p2;

assign res_5_cast_fu_1922_p1 = tmp_16_5_fu_1916_p2;

assign res_6_1_cast_fu_2150_p1 = tmp_16_6_1_fu_2144_p2;

assign res_6_2_cast_fu_2166_p1 = tmp_16_6_2_fu_2160_p2;

assign res_6_3_cast_fu_2182_p1 = tmp_16_6_3_fu_2176_p2;

assign res_6_4_cast_fu_3281_p1 = tmp_16_6_4_reg_3787;

assign res_6_5_fu_3284_p1 = tmp_16_6_5_reg_3792;

assign res_6_6_cast_fu_3287_p1 = tmp_16_6_6_reg_3797;

assign res_6_7_cast_fu_2234_p1 = tmp_16_6_7_fu_2228_p2;

assign res_6_cast_fu_2134_p1 = tmp_16_6_fu_2128_p2;

assign res_7_1_cast_fu_2362_p1 = tmp_16_7_1_fu_2356_p2;

assign res_7_2_cast_fu_2378_p1 = tmp_16_7_2_fu_2372_p2;

assign res_7_3_cast_fu_2394_p1 = tmp_16_7_3_fu_2388_p2;

assign res_7_4_cast_fu_3321_p1 = tmp_16_7_4_reg_3807;

assign res_7_5_fu_3324_p1 = tmp_16_7_5_reg_3812;

assign res_7_6_cast_fu_3327_p1 = tmp_16_7_6_reg_3817;

assign res_7_7_cast_fu_2446_p1 = tmp_16_7_7_fu_2440_p2;

assign res_7_cast_fu_2346_p1 = tmp_16_7_fu_2340_p2;

assign res_8_1_cast_fu_2574_p1 = tmp_16_8_1_fu_2568_p2;

assign res_8_2_cast_fu_2590_p1 = tmp_16_8_2_fu_2584_p2;

assign res_8_3_cast_fu_2606_p1 = tmp_16_8_3_fu_2600_p2;

assign res_8_4_cast_fu_3361_p1 = tmp_16_8_4_reg_3827;

assign res_8_5_fu_3364_p1 = tmp_16_8_5_reg_3832;

assign res_8_6_cast_fu_3367_p1 = tmp_16_8_6_reg_3837;

assign res_8_7_cast_fu_2658_p1 = tmp_16_8_7_fu_2652_p2;

assign res_8_cast_fu_2558_p1 = tmp_16_8_fu_2552_p2;

assign res_9_1_cast_fu_2782_p1 = tmp_16_9_1_fu_2776_p2;

assign res_9_2_cast_fu_2798_p1 = tmp_16_9_2_fu_2792_p2;

assign res_9_3_cast_fu_2814_p1 = tmp_16_9_3_fu_2808_p2;

assign res_9_4_cast_fu_3401_p1 = tmp_16_9_4_reg_3847;

assign res_9_5_fu_3404_p1 = tmp_16_9_5_reg_3852;

assign res_9_6_cast_fu_3407_p1 = tmp_16_9_6_reg_3857;

assign res_9_7_cast_fu_2866_p1 = tmp_16_9_7_fu_2860_p2;

assign res_9_cast_fu_2766_p1 = tmp_16_9_fu_2760_p2;

assign res_cast_59_fu_1286_p1 = tmp_16_2_fu_1280_p2;

assign res_cast_fu_806_p1 = tmp_83_fu_800_p2;

assign sel_tmp1_fu_461_p2 = ((tmp_84_fu_451_p1 == 3'd5) ? 1'b1 : 1'b0);

assign sel_tmp2_fu_467_p2 = ((tmp_84_fu_451_p1 == 3'd4) ? 1'b1 : 1'b0);

assign sel_tmp3_fu_473_p2 = ((tmp_84_fu_451_p1 == 3'd3) ? 1'b1 : 1'b0);

assign sel_tmp4_fu_479_p2 = ((tmp_84_fu_451_p1 == 3'd2) ? 1'b1 : 1'b0);

assign sel_tmp5_fu_485_p2 = ((tmp_84_fu_451_p1 == 3'd1) ? 1'b1 : 1'b0);

assign sel_tmp6_fu_491_p2 = ((tmp_84_fu_451_p1 == 3'd0) ? 1'b1 : 1'b0);

assign sel_tmp_fu_455_p2 = ((tmp_84_fu_451_p1 == 3'd6) ? 1'b1 : 1'b0);

assign sf_1_fu_2902_p2 = (32'd1 + sf_fu_286);

assign tmp100_fu_3296_p2 = (res_6_4_cast_fu_3281_p1 + res_6_6_cast_fu_3287_p1);

assign tmp101_fu_3306_p2 = (tmp99_fu_3290_p2 + tmp262_cast_fu_3302_p1);

assign tmp102_fu_2238_p2 = (res_6_cast_fu_2134_p1 + res_6_3_cast_fu_2182_p1);

assign tmp103_fu_2248_p2 = (res_6_7_cast_fu_2234_p1 + res_6_1_cast_fu_2150_p1);

assign tmp104_fu_2254_p2 = (res_6_2_cast_fu_2166_p1 + tmp103_fu_2248_p2);

assign tmp105_fu_2264_p2 = (tmp264_cast_fu_2244_p1 + tmp265_cast_fu_2260_p1);

assign tmp106_fu_2334_p2 = (tmp_142_fu_2270_p3 ^ p_Result_2_fu_786_p3);

assign tmp107_fu_2350_p2 = (tmp_143_fu_2278_p3 ^ p_Result_2_0_1_fu_810_p3);

assign tmp108_fu_2366_p2 = (tmp_144_fu_2286_p3 ^ p_Result_2_0_2_fu_834_p3);

assign tmp109_fu_2382_p2 = (tmp_145_fu_2294_p3 ^ p_Result_2_0_3_fu_858_p3);

assign tmp10_fu_3056_p2 = (res_0_4_cast_fu_3041_p1 + res_0_6_cast_fu_3047_p1);

assign tmp110_fu_2398_p2 = (tmp_146_fu_2302_p3 ^ p_Result_2_0_4_fu_882_p3);

assign tmp111_fu_2410_p2 = (tmp_147_fu_2310_p3 ^ p_Result_2_0_5_fu_902_p3);

assign tmp112_fu_2422_p2 = (tmp_148_fu_2318_p3 ^ p_Result_2_0_6_fu_922_p3);

assign tmp113_fu_2434_p2 = (tmp_149_fu_2326_p3 ^ p_Result_2_0_7_fu_942_p3);

assign tmp114_fu_3330_p2 = (res_7_5_fu_3324_p1 + p_accu_V_0_7_fu_2985_p3);

assign tmp115_fu_3336_p2 = (res_7_4_cast_fu_3321_p1 + res_7_6_cast_fu_3327_p1);

assign tmp116_fu_3346_p2 = (tmp114_fu_3330_p2 + tmp283_cast_fu_3342_p1);

assign tmp117_fu_2450_p2 = (res_7_cast_fu_2346_p1 + res_7_3_cast_fu_2394_p1);

assign tmp118_fu_2460_p2 = (res_7_7_cast_fu_2446_p1 + res_7_1_cast_fu_2362_p1);

assign tmp119_fu_2466_p2 = (res_7_2_cast_fu_2378_p1 + tmp118_fu_2460_p2);

assign tmp11_fu_3066_p2 = (tmp9_fu_3050_p2 + tmp136_cast_fu_3062_p1);

assign tmp120_fu_2476_p2 = (tmp285_cast_fu_2456_p1 + tmp286_cast_fu_2472_p1);

assign tmp121_fu_2546_p2 = (tmp_150_fu_2482_p3 ^ p_Result_2_fu_786_p3);

assign tmp122_fu_2562_p2 = (tmp_151_fu_2490_p3 ^ p_Result_2_0_1_fu_810_p3);

assign tmp123_fu_2578_p2 = (tmp_152_fu_2498_p3 ^ p_Result_2_0_2_fu_834_p3);

assign tmp124_fu_2594_p2 = (tmp_153_fu_2506_p3 ^ p_Result_2_0_3_fu_858_p3);

assign tmp125_fu_2610_p2 = (tmp_154_fu_2514_p3 ^ p_Result_2_0_4_fu_882_p3);

assign tmp126_fu_2622_p2 = (tmp_155_fu_2522_p3 ^ p_Result_2_0_5_fu_902_p3);

assign tmp127_fu_2634_p2 = (tmp_156_fu_2530_p3 ^ p_Result_2_0_6_fu_922_p3);

assign tmp128_fu_2646_p2 = (tmp_157_fu_2538_p3 ^ p_Result_2_0_7_fu_942_p3);

assign tmp129_fu_3370_p2 = (res_8_5_fu_3364_p1 + p_accu_V_0_8_fu_2978_p3);

assign tmp12_fu_966_p2 = (res_cast_fu_806_p1 + res_0_3_cast_fu_878_p1);

assign tmp130_fu_3376_p2 = (res_8_4_cast_fu_3361_p1 + res_8_6_cast_fu_3367_p1);

assign tmp131_fu_3386_p2 = (tmp129_fu_3370_p2 + tmp304_cast_fu_3382_p1);

assign tmp132_fu_2662_p2 = (res_8_cast_fu_2558_p1 + res_8_3_cast_fu_2606_p1);

assign tmp133_fu_2672_p2 = (res_8_7_cast_fu_2658_p1 + res_8_1_cast_fu_2574_p1);

assign tmp134_fu_2678_p2 = (res_8_2_cast_fu_2590_p1 + tmp133_fu_2672_p2);

assign tmp135_fu_2688_p2 = (tmp306_cast_fu_2668_p1 + tmp307_cast_fu_2684_p1);

assign tmp136_cast_fu_3062_p1 = tmp10_fu_3056_p2;

assign tmp136_fu_2754_p2 = (tmp_158_fu_2694_p1 ^ p_Result_2_fu_786_p3);

assign tmp137_cast_fu_3072_p1 = tmp15_reg_3682;

assign tmp137_fu_2770_p2 = (tmp_159_fu_2698_p3 ^ p_Result_2_0_1_fu_810_p3);

assign tmp138_cast_fu_972_p1 = tmp12_fu_966_p2;

assign tmp138_fu_2786_p2 = (tmp_160_fu_2706_p3 ^ p_Result_2_0_2_fu_834_p3);

assign tmp139_cast_fu_988_p1 = tmp14_fu_982_p2;

assign tmp139_fu_2802_p2 = (tmp_161_fu_2714_p3 ^ p_Result_2_0_3_fu_858_p3);

assign tmp13_fu_976_p2 = (res_0_7_cast_fu_962_p1 + res_0_1_cast_fu_830_p1);

assign tmp140_fu_2818_p2 = (tmp_162_fu_2722_p3 ^ p_Result_2_0_4_fu_882_p3);

assign tmp141_fu_2830_p2 = (tmp_163_fu_2730_p3 ^ p_Result_2_0_5_fu_902_p3);

assign tmp142_fu_2842_p2 = (tmp_164_fu_2738_p3 ^ p_Result_2_0_6_fu_922_p3);

assign tmp143_fu_2854_p2 = (tmp_165_fu_2746_p3 ^ p_Result_2_0_7_fu_942_p3);

assign tmp144_fu_3410_p2 = (res_9_5_fu_3404_p1 + p_accu_V_0_9_fu_2971_p3);

assign tmp145_fu_3416_p2 = (res_9_4_cast_fu_3401_p1 + res_9_6_cast_fu_3407_p1);

assign tmp146_fu_3426_p2 = (tmp144_fu_3410_p2 + tmp325_cast_fu_3422_p1);

assign tmp147_fu_2870_p2 = (res_9_cast_fu_2766_p1 + res_9_3_cast_fu_2814_p1);

assign tmp148_fu_2880_p2 = (res_9_7_cast_fu_2866_p1 + res_9_1_cast_fu_2782_p1);

assign tmp149_fu_2886_p2 = (res_9_2_cast_fu_2798_p1 + tmp148_fu_2880_p2);

assign tmp14_fu_982_p2 = (res_0_2_cast_fu_854_p1 + tmp13_fu_976_p2);

assign tmp150_fu_2896_p2 = (tmp327_cast_fu_2876_p1 + tmp328_cast_fu_2892_p1);

assign tmp157_cast_fu_3102_p1 = tmp25_fu_3096_p2;

assign tmp158_cast_fu_3112_p1 = tmp30_reg_3702;

assign tmp159_cast_fu_1184_p1 = tmp27_fu_1178_p2;

assign tmp15_fu_992_p2 = (tmp138_cast_fu_972_p1 + tmp139_cast_fu_988_p1);

assign tmp160_cast_fu_1200_p1 = tmp29_fu_1194_p2;

assign tmp16_fu_1062_p2 = (tmp_94_fu_998_p3 ^ p_Result_2_fu_786_p3);

assign tmp178_cast_fu_3142_p1 = tmp40_fu_3136_p2;

assign tmp179_cast_fu_3152_p1 = tmp45_reg_3722;

assign tmp17_fu_1078_p2 = (tmp_95_fu_1006_p3 ^ p_Result_2_0_1_fu_810_p3);

assign tmp180_cast_fu_1396_p1 = tmp42_fu_1390_p2;

assign tmp181_cast_fu_1412_p1 = tmp44_fu_1406_p2;

assign tmp18_fu_1094_p2 = (tmp_96_fu_1014_p3 ^ p_Result_2_0_2_fu_834_p3);

assign tmp199_cast_fu_3182_p1 = tmp55_fu_3176_p2;

assign tmp19_fu_1110_p2 = (tmp_97_fu_1022_p3 ^ p_Result_2_0_3_fu_858_p3);

assign tmp1_fu_794_p2 = (tmp_86_fu_722_p3 ^ p_Result_2_fu_786_p3);

assign tmp200_cast_fu_3192_p1 = tmp60_reg_3742;

assign tmp201_cast_fu_1608_p1 = tmp57_fu_1602_p2;

assign tmp202_cast_fu_1624_p1 = tmp59_fu_1618_p2;

assign tmp20_fu_1126_p2 = (tmp_98_fu_1030_p3 ^ p_Result_2_0_4_fu_882_p3);

assign tmp21_fu_1138_p2 = (tmp_99_fu_1038_p3 ^ p_Result_2_0_5_fu_902_p3);

assign tmp220_cast_fu_3222_p1 = tmp70_fu_3216_p2;

assign tmp221_cast_fu_3232_p1 = tmp75_reg_3762;

assign tmp222_cast_fu_1820_p1 = tmp72_fu_1814_p2;

assign tmp223_cast_fu_1836_p1 = tmp74_fu_1830_p2;

assign tmp22_fu_1150_p2 = (tmp_100_fu_1046_p3 ^ p_Result_2_0_6_fu_922_p3);

assign tmp23_fu_1162_p2 = (tmp_101_fu_1054_p3 ^ p_Result_2_0_7_fu_942_p3);

assign tmp241_cast_fu_3262_p1 = tmp85_fu_3256_p2;

assign tmp242_cast_fu_3272_p1 = tmp90_reg_3782;

assign tmp243_cast_fu_2032_p1 = tmp87_fu_2026_p2;

assign tmp244_cast_fu_2048_p1 = tmp89_fu_2042_p2;

assign tmp24_fu_3090_p2 = (res_1_5_fu_3084_p1 + p_accu_V_0_1_fu_3027_p3);

assign tmp25_fu_3096_p2 = (res_1_4_cast_fu_3081_p1 + res_1_6_cast_fu_3087_p1);

assign tmp262_cast_fu_3302_p1 = tmp100_fu_3296_p2;

assign tmp263_cast_fu_3312_p1 = tmp105_reg_3802;

assign tmp264_cast_fu_2244_p1 = tmp102_fu_2238_p2;

assign tmp265_cast_fu_2260_p1 = tmp104_fu_2254_p2;

assign tmp26_fu_3106_p2 = (tmp24_fu_3090_p2 + tmp157_cast_fu_3102_p1);

assign tmp27_fu_1178_p2 = (res_1_cast_fu_1074_p1 + res_1_3_cast_fu_1122_p1);

assign tmp283_cast_fu_3342_p1 = tmp115_fu_3336_p2;

assign tmp284_cast_fu_3352_p1 = tmp120_reg_3822;

assign tmp285_cast_fu_2456_p1 = tmp117_fu_2450_p2;

assign tmp286_cast_fu_2472_p1 = tmp119_fu_2466_p2;

assign tmp28_fu_1188_p2 = (res_1_7_cast_fu_1174_p1 + res_1_1_cast_fu_1090_p1);

assign tmp29_fu_1194_p2 = (res_1_2_cast_fu_1106_p1 + tmp28_fu_1188_p2);

assign tmp2_fu_818_p2 = (tmp_87_fu_730_p3 ^ p_Result_2_0_1_fu_810_p3);

assign tmp304_cast_fu_3382_p1 = tmp130_fu_3376_p2;

assign tmp305_cast_fu_3392_p1 = tmp135_reg_3842;

assign tmp306_cast_fu_2668_p1 = tmp132_fu_2662_p2;

assign tmp307_cast_fu_2684_p1 = tmp134_fu_2678_p2;

assign tmp30_fu_1204_p2 = (tmp159_cast_fu_1184_p1 + tmp160_cast_fu_1200_p1);

assign tmp31_fu_1274_p2 = (tmp_102_fu_1210_p3 ^ p_Result_2_fu_786_p3);

assign tmp325_cast_fu_3422_p1 = tmp145_fu_3416_p2;

assign tmp326_cast_fu_3432_p1 = tmp150_reg_3862;

assign tmp327_cast_fu_2876_p1 = tmp147_fu_2870_p2;

assign tmp328_cast_fu_2892_p1 = tmp149_fu_2886_p2;

assign tmp32_fu_1290_p2 = (tmp_103_fu_1218_p3 ^ p_Result_2_0_1_fu_810_p3);

assign tmp33_fu_1306_p2 = (tmp_104_fu_1226_p3 ^ p_Result_2_0_2_fu_834_p3);

assign tmp34_fu_1322_p2 = (tmp_105_fu_1234_p3 ^ p_Result_2_0_3_fu_858_p3);

assign tmp35_fu_1338_p2 = (tmp_106_fu_1242_p3 ^ p_Result_2_0_4_fu_882_p3);

assign tmp36_fu_1350_p2 = (tmp_107_fu_1250_p3 ^ p_Result_2_0_5_fu_902_p3);

assign tmp37_fu_1362_p2 = (tmp_108_fu_1258_p3 ^ p_Result_2_0_6_fu_922_p3);

assign tmp38_fu_1374_p2 = (tmp_109_fu_1266_p3 ^ p_Result_2_0_7_fu_942_p3);

assign tmp39_fu_3130_p2 = (res_218_5_fu_3124_p1 + p_accu_V_0_2_fu_3020_p3);

assign tmp3_fu_842_p2 = (tmp_88_fu_738_p3 ^ p_Result_2_0_2_fu_834_p3);

assign tmp40_fu_3136_p2 = (res_218_4_cast_fu_3121_p1 + res_218_6_cast_fu_3127_p1);

assign tmp41_fu_3146_p2 = (tmp39_fu_3130_p2 + tmp178_cast_fu_3142_p1);

assign tmp42_fu_1390_p2 = (res_cast_59_fu_1286_p1 + res_218_3_cast_fu_1334_p1);

assign tmp43_fu_1400_p2 = (res_218_7_cast_fu_1386_p1 + res_218_1_cast_fu_1302_p1);

assign tmp44_fu_1406_p2 = (res_218_2_cast_fu_1318_p1 + tmp43_fu_1400_p2);

assign tmp45_fu_1416_p2 = (tmp180_cast_fu_1396_p1 + tmp181_cast_fu_1412_p1);

assign tmp46_fu_1486_p2 = (tmp_110_fu_1422_p3 ^ p_Result_2_fu_786_p3);

assign tmp47_fu_1502_p2 = (tmp_111_fu_1430_p3 ^ p_Result_2_0_1_fu_810_p3);

assign tmp48_fu_1518_p2 = (tmp_112_fu_1438_p3 ^ p_Result_2_0_2_fu_834_p3);

assign tmp49_fu_1534_p2 = (tmp_113_fu_1446_p3 ^ p_Result_2_0_3_fu_858_p3);

assign tmp4_fu_866_p2 = (tmp_89_fu_746_p3 ^ p_Result_2_0_3_fu_858_p3);

assign tmp50_fu_1550_p2 = (tmp_114_fu_1454_p3 ^ p_Result_2_0_4_fu_882_p3);

assign tmp51_fu_1562_p2 = (tmp_115_fu_1462_p3 ^ p_Result_2_0_5_fu_902_p3);

assign tmp52_fu_1574_p2 = (tmp_116_fu_1470_p3 ^ p_Result_2_0_6_fu_922_p3);

assign tmp53_fu_1586_p2 = (tmp_117_fu_1478_p3 ^ p_Result_2_0_7_fu_942_p3);

assign tmp54_fu_3170_p2 = (res_3_5_fu_3164_p1 + p_accu_V_0_3_fu_3013_p3);

assign tmp55_fu_3176_p2 = (res_3_4_cast_fu_3161_p1 + res_3_6_cast_fu_3167_p1);

assign tmp56_fu_3186_p2 = (tmp54_fu_3170_p2 + tmp199_cast_fu_3182_p1);

assign tmp57_fu_1602_p2 = (res_3_cast_fu_1498_p1 + res_3_3_cast_fu_1546_p1);

assign tmp58_fu_1612_p2 = (res_3_7_cast_fu_1598_p1 + res_3_1_cast_fu_1514_p1);

assign tmp59_fu_1618_p2 = (res_3_2_cast_fu_1530_p1 + tmp58_fu_1612_p2);

assign tmp5_fu_890_p2 = (tmp_90_fu_754_p3 ^ p_Result_2_0_4_fu_882_p3);

assign tmp60_fu_1628_p2 = (tmp201_cast_fu_1608_p1 + tmp202_cast_fu_1624_p1);

assign tmp61_fu_1698_p2 = (tmp_118_fu_1634_p3 ^ p_Result_2_fu_786_p3);

assign tmp62_fu_1714_p2 = (tmp_119_fu_1642_p3 ^ p_Result_2_0_1_fu_810_p3);

assign tmp63_fu_1730_p2 = (tmp_120_fu_1650_p3 ^ p_Result_2_0_2_fu_834_p3);

assign tmp64_fu_1746_p2 = (tmp_121_fu_1658_p3 ^ p_Result_2_0_3_fu_858_p3);

assign tmp65_fu_1762_p2 = (tmp_122_fu_1666_p3 ^ p_Result_2_0_4_fu_882_p3);

assign tmp66_fu_1774_p2 = (tmp_123_fu_1674_p3 ^ p_Result_2_0_5_fu_902_p3);

assign tmp67_fu_1786_p2 = (tmp_124_fu_1682_p3 ^ p_Result_2_0_6_fu_922_p3);

assign tmp68_fu_1798_p2 = (tmp_125_fu_1690_p3 ^ p_Result_2_0_7_fu_942_p3);

assign tmp69_fu_3210_p2 = (res_4_5_fu_3204_p1 + p_accu_V_0_4_fu_3006_p3);

assign tmp6_fu_910_p2 = (tmp_91_fu_762_p3 ^ p_Result_2_0_5_fu_902_p3);

assign tmp70_fu_3216_p2 = (res_4_4_cast_fu_3201_p1 + res_4_6_cast_fu_3207_p1);

assign tmp71_fu_3226_p2 = (tmp69_fu_3210_p2 + tmp220_cast_fu_3222_p1);

assign tmp72_fu_1814_p2 = (res_4_cast_fu_1710_p1 + res_4_3_cast_fu_1758_p1);

assign tmp73_fu_1824_p2 = (res_4_7_cast_fu_1810_p1 + res_4_1_cast_fu_1726_p1);

assign tmp74_fu_1830_p2 = (res_4_2_cast_fu_1742_p1 + tmp73_fu_1824_p2);

assign tmp75_fu_1840_p2 = (tmp222_cast_fu_1820_p1 + tmp223_cast_fu_1836_p1);

assign tmp76_fu_1910_p2 = (tmp_126_fu_1846_p3 ^ p_Result_2_fu_786_p3);

assign tmp77_fu_1926_p2 = (tmp_127_fu_1854_p3 ^ p_Result_2_0_1_fu_810_p3);

assign tmp78_fu_1942_p2 = (tmp_128_fu_1862_p3 ^ p_Result_2_0_2_fu_834_p3);

assign tmp79_fu_1958_p2 = (tmp_129_fu_1870_p3 ^ p_Result_2_0_3_fu_858_p3);

assign tmp7_fu_930_p2 = (tmp_92_fu_770_p3 ^ p_Result_2_0_6_fu_922_p3);

assign tmp80_fu_1974_p2 = (tmp_130_fu_1878_p3 ^ p_Result_2_0_4_fu_882_p3);

assign tmp81_fu_1986_p2 = (tmp_131_fu_1886_p3 ^ p_Result_2_0_5_fu_902_p3);

assign tmp82_fu_1998_p2 = (tmp_132_fu_1894_p3 ^ p_Result_2_0_6_fu_922_p3);

assign tmp83_fu_2010_p2 = (tmp_133_fu_1902_p3 ^ p_Result_2_0_7_fu_942_p3);

assign tmp84_fu_3250_p2 = (res_5_5_fu_3244_p1 + p_accu_V_0_5_fu_2999_p3);

assign tmp85_fu_3256_p2 = (res_5_4_cast_fu_3241_p1 + res_5_6_cast_fu_3247_p1);

assign tmp86_fu_3266_p2 = (tmp84_fu_3250_p2 + tmp241_cast_fu_3262_p1);

assign tmp87_fu_2026_p2 = (res_5_cast_fu_1922_p1 + res_5_3_cast_fu_1970_p1);

assign tmp88_fu_2036_p2 = (res_5_7_cast_fu_2022_p1 + res_5_1_cast_fu_1938_p1);

assign tmp89_fu_2042_p2 = (res_5_2_cast_fu_1954_p1 + tmp88_fu_2036_p2);

assign tmp8_fu_950_p2 = (tmp_93_fu_778_p3 ^ p_Result_2_0_7_fu_942_p3);

assign tmp90_fu_2052_p2 = (tmp243_cast_fu_2032_p1 + tmp244_cast_fu_2048_p1);

assign tmp91_fu_2122_p2 = (tmp_134_fu_2058_p3 ^ p_Result_2_fu_786_p3);

assign tmp92_fu_2138_p2 = (tmp_135_fu_2066_p3 ^ p_Result_2_0_1_fu_810_p3);

assign tmp93_fu_2154_p2 = (tmp_136_fu_2074_p3 ^ p_Result_2_0_2_fu_834_p3);

assign tmp94_fu_2170_p2 = (tmp_137_fu_2082_p3 ^ p_Result_2_0_3_fu_858_p3);

assign tmp95_fu_2186_p2 = (tmp_138_fu_2090_p3 ^ p_Result_2_0_4_fu_882_p3);

assign tmp96_fu_2198_p2 = (tmp_139_fu_2098_p3 ^ p_Result_2_0_5_fu_902_p3);

assign tmp97_fu_2210_p2 = (tmp_140_fu_2106_p3 ^ p_Result_2_0_6_fu_922_p3);

assign tmp98_fu_2222_p2 = (tmp_141_fu_2114_p3 ^ p_Result_2_0_7_fu_942_p3);

assign tmp99_fu_3290_p2 = (res_6_5_fu_3284_p1 + p_accu_V_0_6_fu_2992_p3);

assign tmp9_fu_3050_p2 = (res_0_5_fu_3044_p1 + p_accu_V_fu_3034_p3);

assign tmp_100_fu_1046_p3 = weight_V_V_TDATA[32'd70];

assign tmp_101_fu_1054_p3 = weight_V_V_TDATA[32'd71];

assign tmp_102_fu_1210_p3 = weight_V_V_TDATA[32'd56];

assign tmp_103_fu_1218_p3 = weight_V_V_TDATA[32'd57];

assign tmp_104_fu_1226_p3 = weight_V_V_TDATA[32'd58];

assign tmp_105_fu_1234_p3 = weight_V_V_TDATA[32'd59];

assign tmp_106_fu_1242_p3 = weight_V_V_TDATA[32'd60];

assign tmp_107_fu_1250_p3 = weight_V_V_TDATA[32'd61];

assign tmp_108_fu_1258_p3 = weight_V_V_TDATA[32'd62];

assign tmp_109_fu_1266_p3 = weight_V_V_TDATA[32'd63];

assign tmp_110_fu_1422_p3 = weight_V_V_TDATA[32'd48];

assign tmp_111_fu_1430_p3 = weight_V_V_TDATA[32'd49];

assign tmp_112_fu_1438_p3 = weight_V_V_TDATA[32'd50];

assign tmp_113_fu_1446_p3 = weight_V_V_TDATA[32'd51];

assign tmp_114_fu_1454_p3 = weight_V_V_TDATA[32'd52];

assign tmp_115_fu_1462_p3 = weight_V_V_TDATA[32'd53];

assign tmp_116_fu_1470_p3 = weight_V_V_TDATA[32'd54];

assign tmp_117_fu_1478_p3 = weight_V_V_TDATA[32'd55];

assign tmp_118_fu_1634_p3 = weight_V_V_TDATA[32'd40];

assign tmp_119_fu_1642_p3 = weight_V_V_TDATA[32'd41];

assign tmp_120_fu_1650_p3 = weight_V_V_TDATA[32'd42];

assign tmp_121_fu_1658_p3 = weight_V_V_TDATA[32'd43];

assign tmp_122_fu_1666_p3 = weight_V_V_TDATA[32'd44];

assign tmp_123_fu_1674_p3 = weight_V_V_TDATA[32'd45];

assign tmp_124_fu_1682_p3 = weight_V_V_TDATA[32'd46];

assign tmp_125_fu_1690_p3 = weight_V_V_TDATA[32'd47];

assign tmp_126_fu_1846_p3 = weight_V_V_TDATA[32'd32];

assign tmp_127_fu_1854_p3 = weight_V_V_TDATA[32'd33];

assign tmp_128_fu_1862_p3 = weight_V_V_TDATA[32'd34];

assign tmp_129_fu_1870_p3 = weight_V_V_TDATA[32'd35];

assign tmp_130_fu_1878_p3 = weight_V_V_TDATA[32'd36];

assign tmp_131_fu_1886_p3 = weight_V_V_TDATA[32'd37];

assign tmp_132_fu_1894_p3 = weight_V_V_TDATA[32'd38];

assign tmp_133_fu_1902_p3 = weight_V_V_TDATA[32'd39];

assign tmp_134_fu_2058_p3 = weight_V_V_TDATA[32'd24];

assign tmp_135_fu_2066_p3 = weight_V_V_TDATA[32'd25];

assign tmp_136_fu_2074_p3 = weight_V_V_TDATA[32'd26];

assign tmp_137_fu_2082_p3 = weight_V_V_TDATA[32'd27];

assign tmp_138_fu_2090_p3 = weight_V_V_TDATA[32'd28];

assign tmp_139_fu_2098_p3 = weight_V_V_TDATA[32'd29];

assign tmp_140_fu_2106_p3 = weight_V_V_TDATA[32'd30];

assign tmp_141_fu_2114_p3 = weight_V_V_TDATA[32'd31];

assign tmp_142_fu_2270_p3 = weight_V_V_TDATA[32'd16];

assign tmp_143_fu_2278_p3 = weight_V_V_TDATA[32'd17];

assign tmp_144_fu_2286_p3 = weight_V_V_TDATA[32'd18];

assign tmp_145_fu_2294_p3 = weight_V_V_TDATA[32'd19];

assign tmp_146_fu_2302_p3 = weight_V_V_TDATA[32'd20];

assign tmp_147_fu_2310_p3 = weight_V_V_TDATA[32'd21];

assign tmp_148_fu_2318_p3 = weight_V_V_TDATA[32'd22];

assign tmp_149_fu_2326_p3 = weight_V_V_TDATA[32'd23];

assign tmp_150_fu_2482_p3 = weight_V_V_TDATA[32'd8];

assign tmp_151_fu_2490_p3 = weight_V_V_TDATA[32'd9];

assign tmp_152_fu_2498_p3 = weight_V_V_TDATA[32'd10];

assign tmp_153_fu_2506_p3 = weight_V_V_TDATA[32'd11];

assign tmp_154_fu_2514_p3 = weight_V_V_TDATA[32'd12];

assign tmp_155_fu_2522_p3 = weight_V_V_TDATA[32'd13];

assign tmp_156_fu_2530_p3 = weight_V_V_TDATA[32'd14];

assign tmp_157_fu_2538_p3 = weight_V_V_TDATA[32'd15];

assign tmp_158_fu_2694_p1 = weight_V_V_TDATA[0:0];

assign tmp_159_fu_2698_p3 = weight_V_V_TDATA[32'd1];

assign tmp_160_fu_2706_p3 = weight_V_V_TDATA[32'd2];

assign tmp_161_fu_2714_p3 = weight_V_V_TDATA[32'd3];

assign tmp_162_fu_2722_p3 = weight_V_V_TDATA[32'd4];

assign tmp_163_fu_2730_p3 = weight_V_V_TDATA[32'd5];

assign tmp_164_fu_2738_p3 = weight_V_V_TDATA[32'd6];

assign tmp_165_fu_2746_p3 = weight_V_V_TDATA[32'd7];

assign tmp_16_0_1_fu_824_p2 = (tmp2_fu_818_p2 ^ 1'd1);

assign tmp_16_0_2_fu_848_p2 = (tmp3_fu_842_p2 ^ 1'd1);

assign tmp_16_0_3_fu_872_p2 = (tmp4_fu_866_p2 ^ 1'd1);

assign tmp_16_0_4_fu_896_p2 = (tmp5_fu_890_p2 ^ 1'd1);

assign tmp_16_0_5_fu_916_p2 = (tmp6_fu_910_p2 ^ 1'd1);

assign tmp_16_0_6_fu_936_p2 = (tmp7_fu_930_p2 ^ 1'd1);

assign tmp_16_0_7_fu_956_p2 = (tmp8_fu_950_p2 ^ 1'd1);

assign tmp_16_1_1_fu_1084_p2 = (tmp17_fu_1078_p2 ^ 1'd1);

assign tmp_16_1_2_fu_1100_p2 = (tmp18_fu_1094_p2 ^ 1'd1);

assign tmp_16_1_3_fu_1116_p2 = (tmp19_fu_1110_p2 ^ 1'd1);

assign tmp_16_1_4_fu_1132_p2 = (tmp20_fu_1126_p2 ^ 1'd1);

assign tmp_16_1_5_fu_1144_p2 = (tmp21_fu_1138_p2 ^ 1'd1);

assign tmp_16_1_6_fu_1156_p2 = (tmp22_fu_1150_p2 ^ 1'd1);

assign tmp_16_1_7_fu_1168_p2 = (tmp23_fu_1162_p2 ^ 1'd1);

assign tmp_16_1_fu_1068_p2 = (tmp16_fu_1062_p2 ^ 1'd1);

assign tmp_16_2_1_fu_1296_p2 = (tmp32_fu_1290_p2 ^ 1'd1);

assign tmp_16_2_2_fu_1312_p2 = (tmp33_fu_1306_p2 ^ 1'd1);

assign tmp_16_2_3_fu_1328_p2 = (tmp34_fu_1322_p2 ^ 1'd1);

assign tmp_16_2_4_fu_1344_p2 = (tmp35_fu_1338_p2 ^ 1'd1);

assign tmp_16_2_5_fu_1356_p2 = (tmp36_fu_1350_p2 ^ 1'd1);

assign tmp_16_2_6_fu_1368_p2 = (tmp37_fu_1362_p2 ^ 1'd1);

assign tmp_16_2_7_fu_1380_p2 = (tmp38_fu_1374_p2 ^ 1'd1);

assign tmp_16_2_fu_1280_p2 = (tmp31_fu_1274_p2 ^ 1'd1);

assign tmp_16_3_1_fu_1508_p2 = (tmp47_fu_1502_p2 ^ 1'd1);

assign tmp_16_3_2_fu_1524_p2 = (tmp48_fu_1518_p2 ^ 1'd1);

assign tmp_16_3_3_fu_1540_p2 = (tmp49_fu_1534_p2 ^ 1'd1);

assign tmp_16_3_4_fu_1556_p2 = (tmp50_fu_1550_p2 ^ 1'd1);

assign tmp_16_3_5_fu_1568_p2 = (tmp51_fu_1562_p2 ^ 1'd1);

assign tmp_16_3_6_fu_1580_p2 = (tmp52_fu_1574_p2 ^ 1'd1);

assign tmp_16_3_7_fu_1592_p2 = (tmp53_fu_1586_p2 ^ 1'd1);

assign tmp_16_3_fu_1492_p2 = (tmp46_fu_1486_p2 ^ 1'd1);

assign tmp_16_4_1_fu_1720_p2 = (tmp62_fu_1714_p2 ^ 1'd1);

assign tmp_16_4_2_fu_1736_p2 = (tmp63_fu_1730_p2 ^ 1'd1);

assign tmp_16_4_3_fu_1752_p2 = (tmp64_fu_1746_p2 ^ 1'd1);

assign tmp_16_4_4_fu_1768_p2 = (tmp65_fu_1762_p2 ^ 1'd1);

assign tmp_16_4_5_fu_1780_p2 = (tmp66_fu_1774_p2 ^ 1'd1);

assign tmp_16_4_6_fu_1792_p2 = (tmp67_fu_1786_p2 ^ 1'd1);

assign tmp_16_4_7_fu_1804_p2 = (tmp68_fu_1798_p2 ^ 1'd1);

assign tmp_16_4_fu_1704_p2 = (tmp61_fu_1698_p2 ^ 1'd1);

assign tmp_16_5_1_fu_1932_p2 = (tmp77_fu_1926_p2 ^ 1'd1);

assign tmp_16_5_2_fu_1948_p2 = (tmp78_fu_1942_p2 ^ 1'd1);

assign tmp_16_5_3_fu_1964_p2 = (tmp79_fu_1958_p2 ^ 1'd1);

assign tmp_16_5_4_fu_1980_p2 = (tmp80_fu_1974_p2 ^ 1'd1);

assign tmp_16_5_5_fu_1992_p2 = (tmp81_fu_1986_p2 ^ 1'd1);

assign tmp_16_5_6_fu_2004_p2 = (tmp82_fu_1998_p2 ^ 1'd1);

assign tmp_16_5_7_fu_2016_p2 = (tmp83_fu_2010_p2 ^ 1'd1);

assign tmp_16_5_fu_1916_p2 = (tmp76_fu_1910_p2 ^ 1'd1);

assign tmp_16_6_1_fu_2144_p2 = (tmp92_fu_2138_p2 ^ 1'd1);

assign tmp_16_6_2_fu_2160_p2 = (tmp93_fu_2154_p2 ^ 1'd1);

assign tmp_16_6_3_fu_2176_p2 = (tmp94_fu_2170_p2 ^ 1'd1);

assign tmp_16_6_4_fu_2192_p2 = (tmp95_fu_2186_p2 ^ 1'd1);

assign tmp_16_6_5_fu_2204_p2 = (tmp96_fu_2198_p2 ^ 1'd1);

assign tmp_16_6_6_fu_2216_p2 = (tmp97_fu_2210_p2 ^ 1'd1);

assign tmp_16_6_7_fu_2228_p2 = (tmp98_fu_2222_p2 ^ 1'd1);

assign tmp_16_6_fu_2128_p2 = (tmp91_fu_2122_p2 ^ 1'd1);

assign tmp_16_7_1_fu_2356_p2 = (tmp107_fu_2350_p2 ^ 1'd1);

assign tmp_16_7_2_fu_2372_p2 = (tmp108_fu_2366_p2 ^ 1'd1);

assign tmp_16_7_3_fu_2388_p2 = (tmp109_fu_2382_p2 ^ 1'd1);

assign tmp_16_7_4_fu_2404_p2 = (tmp110_fu_2398_p2 ^ 1'd1);

assign tmp_16_7_5_fu_2416_p2 = (tmp111_fu_2410_p2 ^ 1'd1);

assign tmp_16_7_6_fu_2428_p2 = (tmp112_fu_2422_p2 ^ 1'd1);

assign tmp_16_7_7_fu_2440_p2 = (tmp113_fu_2434_p2 ^ 1'd1);

assign tmp_16_7_fu_2340_p2 = (tmp106_fu_2334_p2 ^ 1'd1);

assign tmp_16_8_1_fu_2568_p2 = (tmp122_fu_2562_p2 ^ 1'd1);

assign tmp_16_8_2_fu_2584_p2 = (tmp123_fu_2578_p2 ^ 1'd1);

assign tmp_16_8_3_fu_2600_p2 = (tmp124_fu_2594_p2 ^ 1'd1);

assign tmp_16_8_4_fu_2616_p2 = (tmp125_fu_2610_p2 ^ 1'd1);

assign tmp_16_8_5_fu_2628_p2 = (tmp126_fu_2622_p2 ^ 1'd1);

assign tmp_16_8_6_fu_2640_p2 = (tmp127_fu_2634_p2 ^ 1'd1);

assign tmp_16_8_7_fu_2652_p2 = (tmp128_fu_2646_p2 ^ 1'd1);

assign tmp_16_8_fu_2552_p2 = (tmp121_fu_2546_p2 ^ 1'd1);

assign tmp_16_9_1_fu_2776_p2 = (tmp137_fu_2770_p2 ^ 1'd1);

assign tmp_16_9_2_fu_2792_p2 = (tmp138_fu_2786_p2 ^ 1'd1);

assign tmp_16_9_3_fu_2808_p2 = (tmp139_fu_2802_p2 ^ 1'd1);

assign tmp_16_9_4_fu_2824_p2 = (tmp140_fu_2818_p2 ^ 1'd1);

assign tmp_16_9_5_fu_2836_p2 = (tmp141_fu_2830_p2 ^ 1'd1);

assign tmp_16_9_6_fu_2848_p2 = (tmp142_fu_2842_p2 ^ 1'd1);

assign tmp_16_9_7_fu_2860_p2 = (tmp143_fu_2854_p2 ^ 1'd1);

assign tmp_16_9_fu_2760_p2 = (tmp136_fu_2754_p2 ^ 1'd1);

assign tmp_6_fu_716_p2 = ((sf_fu_286 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_83_fu_800_p2 = (tmp1_fu_794_p2 ^ 1'd1);

assign tmp_84_fu_451_p1 = sf_fu_286[2:0];

assign tmp_86_fu_722_p3 = weight_V_V_TDATA[32'd72];

assign tmp_87_fu_730_p3 = weight_V_V_TDATA[32'd73];

assign tmp_88_fu_738_p3 = weight_V_V_TDATA[32'd74];

assign tmp_89_fu_746_p3 = weight_V_V_TDATA[32'd75];

assign tmp_90_fu_754_p3 = weight_V_V_TDATA[32'd76];

assign tmp_91_fu_762_p3 = weight_V_V_TDATA[32'd77];

assign tmp_92_fu_770_p3 = weight_V_V_TDATA[32'd78];

assign tmp_93_fu_778_p3 = weight_V_V_TDATA[32'd79];

assign tmp_94_fu_998_p3 = weight_V_V_TDATA[32'd64];

assign tmp_95_fu_1006_p3 = weight_V_V_TDATA[32'd65];

assign tmp_96_fu_1014_p3 = weight_V_V_TDATA[32'd66];

assign tmp_97_fu_1022_p3 = weight_V_V_TDATA[32'd67];

assign tmp_98_fu_1030_p3 = weight_V_V_TDATA[32'd68];

assign tmp_99_fu_1038_p3 = weight_V_V_TDATA[32'd69];

assign tmp_9_fu_2908_p2 = ((sf_1_fu_2902_p2 == 32'd8) ? 1'b1 : 1'b0);

assign tmp_fu_391_p2 = ((nf_fu_290 == 32'd0) ? 1'b1 : 1'b0);

endmodule //StreamingFCLayer_Batch_3_Matrix_Vector_Activa
