# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xcku115-flva1517-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/justin/paulchowresearch2020/Galapagos/finn_galapagos_bridge/axis_galapagos_bridge/finn_galapagos_bridge.cache/wt [current_project]
set_property parent.project_path /home/justin/paulchowresearch2020/Galapagos/finn_galapagos_bridge/axis_galapagos_bridge/finn_galapagos_bridge.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  /home/justin/paulchowresearch2020/Galapagos/galapagos/middleware/finn
  /home/justin/paulchowresearch2020/Galapagos/finn_galapagos_bridge/ip-bridge/ip_axis_galapagos_bridge
  /home/justin/paulchowresearch2020/FINN/finn_container_files/ip/code_gen_ipgen_StreamingFCLayer_Batch_0_5ufxrklk/project_StreamingFCLayer_Batch_0/sol1/impl
} [current_project]
update_ip_catalog
set_property ip_output_repo /home/justin/paulchowresearch2020/Galapagos/finn_galapagos_bridge/axis_galapagos_bridge/finn_galapagos_bridge.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/justin/paulchowresearch2020/Galapagos/finn_galapagos_bridge/shared-ip/data_width_converter.v
  /home/justin/paulchowresearch2020/Galapagos/finn_galapagos_bridge/axis_galapagos_bridge/finn_galapagos_bridge.srcs/sources_1/new/axis_galapagos_bridge.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top axi_stream_to_galapagos_bridge -part xcku115-flva1517-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef axi_stream_to_galapagos_bridge.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file axi_stream_to_galapagos_bridge_utilization_synth.rpt -pb axi_stream_to_galapagos_bridge_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
