set_property SRC_FILE_INFO {cfile:/home/justin/paulchowresearch2020/Galapagos/finn_galapagos_bridge/bridge_deployment_test/deployment_test_project/Sidewinder_Board_and_XDC_files_20190923/sidewinder_io_constraints.xdc rfile:../../../Sidewinder_Board_and_XDC_files_20190923/sidewinder_io_constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C4 [get_ports {sysclk100_clk_p[0]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C3 [get_ports {sysclk100_clk_n[0]}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  N13   [get_ports    sysclk200_p                ]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  M13   [get_ports    sysclk200_n                ]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  B6    [get_ports {  pb_sw[0]                  }]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  A3    [get_ports {  pb_sw[1]                  }]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  B3    [get_ports {  pb_sw[2]                  }]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  B5    [get_ports {  led[0]                    }]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  A5    [get_ports {  led[1]                    }]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  A4    [get_ports {  led[2]                    }]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  C5    [get_ports {  led[3]                    }]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  C6    [get_ports {  led[4]                    }]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  C1    [get_ports {  led[5]                    }]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  D2    [get_ports {  led[6]                    }]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  D3    [get_ports {  led[7]                    }]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  D4    [get_ports {  led[8]                    }]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  D1    [get_ports {  led[9]                    }]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R33 [get_ports clk_qsfp0_n]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R32 [get_ports clk_qsfp0_p]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L33 [get_ports clk_qsfp1_n]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L32 [get_ports clk_qsfp1_p]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L41 [get_ports qsfp0_rx_p[0]]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L42 [get_ports qsfp0_rx_n[0]]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K39 [get_ports qsfp0_rx_p[1]]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K40 [get_ports qsfp0_rx_n[1]]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J41 [get_ports qsfp0_rx_p[2]]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J42 [get_ports qsfp0_rx_n[2]]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H39 [get_ports qsfp0_rx_p[3]]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H40 [get_ports qsfp0_rx_n[3]]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M34 [get_ports qsfp0_tx_p[0]]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M35 [get_ports qsfp0_tx_n[0]]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L36 [get_ports qsfp0_tx_p[1]]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L37 [get_ports qsfp0_tx_n[1]]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K34 [get_ports qsfp0_tx_p[2]]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K35 [get_ports qsfp0_tx_n[2]]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J36 [get_ports qsfp0_tx_p[3]]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J37 [get_ports qsfp0_tx_n[3]]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G41 [get_ports qsfp1_rx_p[0]]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G42 [get_ports qsfp1_rx_n[0]]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F39 [get_ports qsfp1_rx_p[1]]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F40 [get_ports qsfp1_rx_n[1]]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E41 [get_ports qsfp1_rx_p[2]]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E42 [get_ports qsfp1_rx_n[2]]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D39 [get_ports qsfp1_rx_p[3]]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D40 [get_ports qsfp1_rx_n[3]]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H34 [get_ports qsfp1_tx_p[0]]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H35 [get_ports qsfp1_tx_n[0]]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G36 [get_ports qsfp1_tx_p[1]]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G37 [get_ports qsfp1_tx_n[1]]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F34 [get_ports qsfp1_tx_p[2]]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F35 [get_ports qsfp1_tx_n[2]]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E36 [get_ports qsfp1_tx_p[3]]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E37 [get_ports qsfp1_tx_n[3]]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  Y12   [get_ports    nvme_u2_north_refclk0_p    ]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  Y11   [get_ports    nvme_u2_north_refclk0_n    ]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  AB12  [get_ports    nvme_u2_south_refclk0_p    ]
